/* Generated by Together */
package ch8;
public class DateTimeThings {
    public String toString() {
        long elapsed = endTime - startTime;
        long ss = elapsed / 1000;
        long mm = elapsed % 1000;
        return "Elapsed time: seconds:"+ ss+ ", milliseconds:"+ mm;
    }

    public void startTiming() {
		startTime = System.currentTimeMillis();
    }

    public void endTiming() {
   		endTime = System.currentTimeMillis();
    }

    public void displayElapsedTime() {
        System.out.println(this);
    }

    public static void main(String[] argv) {
		DateTimeThings me = new DateTimeThings();
		String blankString = new String();
        StringBuffer blankStringBuffer = new StringBuffer();
        int iters = 100000;

        me.startTiming();
        for(int i = 0; i< iters; i++)
            blankString+=" ";
        me.endTiming();
        me.displayElapsedTime();

        me.startTiming();
        for(int i = 0; i< iters; i++)
            blankStringBuffer.append(" ");
        me.endTiming();
        me.displayElapsedTime();

    }

    private long endTime;
    private long startTime;
}
