/* Generated by Together */
package ch8;

import java.text.SimpleDateFormat;
import java.util.Date;

public class DatFmt {
	public DatFmt() {
	}

	public DatFmt(int format) {
		this();
		this.format = format;
	}

	public DatFmt(int format, char separator) {
		this(format);
		this.separator = separator;
	}

	public int getFormat() {
		return format;
	}

	public void setFormat(int format) {
		this.format = format;
	}

	public char getSeparator() {
		return separator;
	}

	public void setSeparator(char separator) {
		if (separator == -1)
			separator = separator;
		this.separator = separator;
	}

	public String format(Date date) {
		SimpleDateFormat simpel = new SimpleDateFormat(formats[format]);
		String dateString = simpel.format(date);
		dateString = dateString.replace('/', defaultSeparators[format]);
		return dateString;
	}

	public String format(Date date, char separator) {
		SimpleDateFormat simpel = new SimpleDateFormat(formats[format]);
		String dateString = simpel.format(date);
		dateString = dateString.replace('/', separator);
		return dateString;
	}

	public static void main(String[] argv) {
		DatFmt me = new DatFmt();
		Date date = new Date();
		System.out.println(me.format(date));
		System.out.println("Default separator\n");
		for (int i = DATFMT_MDY; i <= DATFMT_JIS; i++) {
			me.setFormat(i);
			System.out.println(me.format(date));
		}

		System.out.println("Forced separator\n");
		for (int i = DATFMT_MDY; i <= DATFMT_JIS; i++) {
			me.setFormat(i);
			me.setSeparator('.');
			System.out.println(me.format(date, me.getSeparator()));
		}
	}

	public final static int DATFMT_MDY = 0;
	public final static int DATFMT_DMY = 1;
	public final static int DATFMT_YMD = 2;
	public final static int DATFMT_JUL = 3;
	public final static int DATFMT_USA = 4;
	public final static int DATFMT_EUR = 5;
	public final static int DATFMT_ISO = 6;
	public final static int DATFMT_JIS = 7;

	private int format = DATFMT_ISO;
	private char separator = (char) - 1;

	private String[] formats =
		{
			"MM/dd/yy",
			"dd/MM/yy",
			"yy/MM/dd",
			"yy/ddd",
			"MM/dd/yyyy",
			"dd/MM/yyyy",
			"yyyy/MM/dd",
			"yyyy/MM/dd" };
	private char[] defaultSeparators =
		{ '/', '/', '/', '/', '/', '.', '-', '-' };

}
