/* Generated by Together */

package tegenpartijen;

/**
 * Een adres van een tegenpartij!
 * @stereotype type
 * @author Mathy
 * @version 1.0 
 */
public class Adres {
    public Adres(String straat, int nummer, String gemeente, int postcode, boolean hooofdVerblijfplaats) {
	setStraat(straat);
        setPostcode(postcode);
        setGemeente(gemeente);
        setNummer(nummer);
        setHoofdVerblijfplaats(hoofdVerblijfplaats);
    }

    public int getNummer(){ return nummer; }

    public void setNummer(int nummer){ this.nummer = nummer; }

    public String getStraat(){ return straat; }

    public void setStraat(String straat){ this.straat = straat; }

    public String getGemeente(){ return gemeente; }

    public void setGemeente(String gemeente){ this.gemeente = gemeente; }

    public int getPostcode(){ return postcode; }

    public void setPostcode(int postcode){ this.postcode = postcode; }

    public boolean isHoofdVerblijfplaats() {
        return hoofdVerblijfplaats;
    }

    public void setHoofdVerblijfplaats(boolean hoofdVerblijfplaats) {
        this.hoofdVerblijfplaats = hoofdVerblijfplaats;
    }

    public String toString() {
        return straat+"\n"+postcode+" "+gemeente+"\n";
    }

    private int nummer;
    private String straat;
    private String gemeente;
    private int postcode;
    private boolean hoofdVerblijfplaats;
}
