/* Generated by Together */

package tegenpartijen;

import java.util.*;

 public class RetailTegenpartij extends ATegenpartij {
    public RetailTegenpartij(String naam, String voornaam, SoortRelatie soortRelatie, Vector adressen) {
        super(naam, soortRelatie);
        setVoornaam(voornaam);
        this.adressen = adressen;
    }

    public String getVoornaam(){ return voornaam; }

    public void setVoornaam(String voornaam){ this.voornaam = voornaam; }

    public String toonNaam() {
        return "\n"+super.toString()+" "+voornaam;
    }

    public String toonAdresGegevens() {
        String adres = "\n";
        for(int i =0; i<adressen.size(); i++){
            if(!((Adres)adressen.elementAt(i)).isHoofdVerblijfplaats())
                adres = "Hoofdverblijf\n";
           	else
                adres = "Secundair verblijf\n";
			adres += (Adres)(adressen.elementAt(i));
            adres += "\n";
        }
        return adres+="\n";
    }

    public String toString() {
		return toonNaam()+toonAdresGegevens();
    }

    private String voornaam;
    private Vector adressen;
}
