/* Generated by Together */

package tegenpartijen;

public class SoortRelatie {
    public SoortRelatie(int type, String omschrijving) {
        setType(type);
        setOmschrijving(omschrijving);
    }

    public int getType(){ return type; }

    public void setType(int type){ this.type = type; }

    public String getOmschrijving(){ return omschrijving; }

    public void setOmschrijving(String omschrijving){ this.omschrijving = omschrijving; }

    public String toString() {
        return "\n"+omschrijving+"Classificatie: "+type;
    }

    private int type;
    private String omschrijving;
}
