/* Generated by Together */

package tegenpartijen;

/**
 * Een Tegenpartij is iedereen waarmee KBC een commerciële relatie heeft!
 * @author Mathy
 * @version 1.0
 * @stereotype type 
 */
public interface Tegenpartijen {
    String toString();

    String toonNaam();

    String toonAdresGegevens();
}
