/* Generated by Together */

package database.datastore;

/**
 * @persistent
 * @rdbPhysicalName FINMAS 
 */
public class FINMAS {
    public FINMAS() {
    }

    /**
     * Numéro société
     * @rdbPhysicalName NSOCIN
     * @rdbNotNull
     * @rdbSize 2
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double NSOCIN;

    /**
     * Temp Number
     * @rdbPhysicalName NINTIN
     * @rdbNotNull
     * @rdbSize 7
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double NINTIN;

    /**
     * Code inactivité
     * @rdbPhysicalName CINAIN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CINAIN;

    /**
     * Nom de l'intérimaire
     * @rdbPhysicalName NOMIIN
     * @rdbNotNull
     * @rdbSize 25
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String NOMIIN;

    /**
     * Prénom
     * @rdbPhysicalName PRNMIN
     * @rdbNotNull
     * @rdbSize 20
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String PRNMIN;

    /**
     * Initiales autres prénoms
     * @rdbPhysicalName INITIN
     * @rdbNotNull
     * @rdbSize 10
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String INITIN;

    /**
     * SIECLE
     * @rdbPhysicalName SNAIIN
     * @rdbNotNull
     * @rdbSize 2
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double SNAIIN;

    /**
     * Date de naissance de l'intérimaire
     * @rdbPhysicalName DNAIIN
     * @rdbNotNull
     * @rdbSize 8
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double DNAIIN;

    /**
     * Numéro de succursale
     * @rdbPhysicalName SUCGIN
     * @rdbNotNull
     * @rdbSize 3
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double SUCGIN;

    /**
     * Adresse
     * @rdbPhysicalName ADRDIN
     * @rdbNotNull
     * @rdbSize 25
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String ADRDIN;

    /**
     * Numéro d'immeuble
     * @rdbPhysicalName NMADIN
     * @rdbNotNull
     * @rdbSize 5
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String NMADIN;

    /**
     * Numéro de  boîte
     * @rdbPhysicalName NBODIN
     * @rdbNotNull
     * @rdbSize 4
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String NBODIN;

    /**
     * Code pays
     * @rdbPhysicalName CPADIN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CPADIN;

    /**
     * Numéro canton postal
     * @rdbPhysicalName NPODIN
     * @rdbNotNull
     * @rdbSize 6
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String NPODIN;

    /**
     * Localité
     * @rdbPhysicalName LOCDIN
     * @rdbNotNull
     * @rdbSize 25
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String LOCDIN;

    /**
     * Numéro de téléphone
     * @rdbPhysicalName PHNRIN
     * @rdbNotNull
     * @rdbSize 15
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String PHNRIN;

    /**
     * C/O (residence)
     * @rdbPhysicalName COREIN
     * @rdbNotNull
     * @rdbSize 30
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String COREIN;

    /**
     * Adresse de la résidence
     * @rdbPhysicalName ADRRIN
     * @rdbNotNull
     * @rdbSize 25
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String ADRRIN;

    /**
     * Numéro d'immeuble de la résidence
     * @rdbPhysicalName NMARIN
     * @rdbNotNull
     * @rdbSize 5
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String NMARIN;

    /**
     * Numéro de boîte de la résidence
     * @rdbPhysicalName NBORIN
     * @rdbNotNull
     * @rdbSize 4
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String NBORIN;

    /**
     * Code pays de la résidence
     * @rdbPhysicalName CPARIN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CPARIN;

    /**
     * Numéro canton postal de la résidence
     * @rdbPhysicalName NPORIN
     * @rdbNotNull
     * @rdbSize 6
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String NPORIN;

    /**
     * Localité résidence
     * @rdbPhysicalName LOCRIN
     * @rdbNotNull
     * @rdbSize 25
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String LOCRIN;

    /**
     * Numéro de téléphone résidence
     * @rdbPhysicalName PHRRIN
     * @rdbNotNull
     * @rdbSize 15
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String PHRRIN;

    /**
     * Code adresse domicile exacte
     * @rdbPhysicalName ADOKIN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String ADOKIN;

    /**
     * Code adresse résidence ok
     * @rdbPhysicalName ADRKIN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String ADRKIN;

    /**
     * ENVOI DOCUMENTS EN SUCCURSALE
     * @rdbPhysicalName CDOSIN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CDOSIN;

    /**
     * Code état-civil
     * @rdbPhysicalName CETCIN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CETCIN;

    /**
     * Code civilité
     * @rdbPhysicalName CCIVIN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CCIVIN;

    /**
     * Code sexe
     * @rdbPhysicalName SEXEIN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String SEXEIN;

    /**
     * Code langue
     * @rdbPhysicalName CLANIN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CLANIN;

    /**
     * Numéro Registre National
     * @rdbPhysicalName NRGNIN
     * @rdbNotNull
     * @rdbSize 11
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL 
     */
    private double NRGNIN;

    /**
     * LIEU DE NAISSANCE
     * @rdbPhysicalName LNAIIN
     * @rdbNotNull
     * @rdbSize 25
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String LNAIIN;

    /**
     * Code pays de naissance ONSS
     * @rdbPhysicalName CPANIN
     * @rdbNotNull
     * @rdbSize 3
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL 
     */
    private double CPANIN;

    /**
     * Code nationalité
     * @rdbPhysicalName CNATIN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CNATIN;

    /**
     * OUVRIER
     * @rdbPhysicalName COUVIN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String COUVIN;

    /**
     * EMPLOYE
     * @rdbPhysicalName CEMLIN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CEMLIN;

    /**
     * Code service médical autorisé
     * @rdbPhysicalName CSMAIN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CSMAIN;

    /**
     * Code étudiant
     * @rdbPhysicalName CETUIN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CETUIN;

    /**
     * SIECLE
     * @rdbPhysicalName SENSIN
     * @rdbNotNull
     * @rdbSize 2
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double SENSIN;

    /**
     * Date d'entrée en service
     * @rdbPhysicalName DENSIN
     * @rdbNotNull
     * @rdbSize 8
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double DENSIN;

    /**
     * SIECLE
     * @rdbPhysicalName S1TRIN
     * @rdbNotNull
     * @rdbSize 2
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double S1TRIN;

    /**
     * Date première mise au travail - annee
     * @rdbPhysicalName D1TRIN
     * @rdbNotNull
     * @rdbSize 8
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double D1TRIN;

    /**
     * SIECLE
     * @rdbPhysicalName SDACIN
     * @rdbNotNull
     * @rdbSize 2
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double SDACIN;

    /**
     * Date dernière activité
     * @rdbPhysicalName DDACIN
     * @rdbNotNull
     * @rdbSize 8
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double DDACIN;

    /**
     * Nom du conjoint
     * @rdbPhysicalName NOMEIN
     * @rdbNotNull
     * @rdbSize 25
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String NOMEIN;

    /**
     * Date de naissance du conjoint
     * @rdbPhysicalName DNCNIN
     * @rdbNotNull
     * @rdbSize 8
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double DNCNIN;

    /**
     * Code profession du conjoint
     * @rdbPhysicalName CPRCIN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CPRCIN;

    /**
     * Mode de paiement
     * @rdbPhysicalName MODPIN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String MODPIN;

    /**
     * Numéro de compte bancaire
     * @rdbPhysicalName NCBNIN
     * @rdbNotNull
     * @rdbSize 12
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL 
     */
    private double NCBNIN;

    /**
     * Nom du titulaire du compte bancaire
     * @rdbPhysicalName NOMBIN
     * @rdbNotNull
     * @rdbSize 25
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String NOMBIN;

    /**
     * Code civilité bénéficiaire
     * @rdbPhysicalName CCIBIN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CCIBIN;

    /**
     * Adresse du bénéficiaire du compte
     * @rdbPhysicalName ADRBIN
     * @rdbNotNull
     * @rdbSize 25
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String ADRBIN;

    /**
     * Code postal du bénéficiaire
     * @rdbPhysicalName NPOBIN
     * @rdbNotNull
     * @rdbSize 6
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String NPOBIN;

    /**
     * Localité du bénéficiaire
     * @rdbPhysicalName LOCBIN
     * @rdbNotNull
     * @rdbSize 25
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String LOCBIN;

    /**
     * Code pays du bénéficiaire
     * @rdbPhysicalName CPABIN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CPABIN;

    /**
     * code soumis a l' onss
     * @rdbPhysicalName CSOSIN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CSOSIN;

    /**
     * Code travailleur frontalier
     * @rdbPhysicalName CTFRIN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CTFRIN;

    /**
     * SIECLE
     * @rdbPhysicalName SDEFIN
     * @rdbNotNull
     * @rdbSize 2
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double SDEFIN;

    /**
     * Date début attestation frontalier
     * @rdbPhysicalName DDEFIN
     * @rdbNotNull
     * @rdbSize 8
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double DDEFIN;

    /**
     * SIECLE
     * @rdbPhysicalName SFEFIN
     * @rdbNotNull
     * @rdbSize 2
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double SFEFIN;

    /**
     * Date péremption attestation frontalier
     * @rdbPhysicalName DFEFIN
     * @rdbNotNull
     * @rdbSize 8
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double DFEFIN;

    /**
     * Pourcentage précompte
     * @rdbPhysicalName PCPRIN
     * @rdbNotNull
     * @rdbSize 5
     * @rdbDigits 2
     * @rdbLogicalType DECIMAL 
     */
    private double PCPRIN;

    /**
     * CONJOINT A CHARGE
     * @rdbPhysicalName ACCNIN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String ACCNIN;

    /**
     * Nombre d' enfants a charge
     * @rdbPhysicalName ACENIN
     * @rdbNotNull
     * @rdbSize 3
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL 
     */
    private double ACENIN;

    /**
     * Autres personnes a charge
     * @rdbPhysicalName ACAPIN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL 
     */
    private double ACAPIN;

    /**
     * Type document identité
     * @rdbPhysicalName TDOIIN
     * @rdbNotNull
     * @rdbSize 3
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String TDOIIN;

    /**
     * Numéro de la carte d'identité
     * @rdbPhysicalName NCIDIN
     * @rdbNotNull
     * @rdbSize 12
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String NCIDIN;

    /**
     * commune emmettrice document
     * @rdbPhysicalName CCEMIN
     * @rdbNotNull
     * @rdbSize 25
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CCEMIN;

    /**
     * Type de permis de travail
     * @rdbPhysicalName TCTRIN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String TCTRIN;

    /**
     * Numéro du permis de travail
     * @rdbPhysicalName NCTRIN
     * @rdbNotNull
     * @rdbSize 12
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String NCTRIN;

    /**
     * Suspension reason SZR
     * @rdbPhysicalName CCETIN
     * @rdbNotNull
     * @rdbSize 25
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CCETIN;

    /**
     * Saisie forfaitaire mensuelleouvrier
     * @rdbPhysicalName SSFOIN
     * @rdbNotNull
     * @rdbSize 9
     * @rdbDigits 2
     * @rdbLogicalType DECIMAL 
     */
    private double SSFOIN;

    /**
     * Saisie forfaitaire mensuellerégime employé
     * @rdbPhysicalName SSFEIN
     * @rdbNotNull
     * @rdbSize 9
     * @rdbDigits 2
     * @rdbLogicalType DECIMAL 
     */
    private double SSFEIN;

    /**
     * MONTANT TOTAL A SAISIR
     * @rdbPhysicalName SSMOIN
     * @rdbNotNull
     * @rdbSize 11
     * @rdbDigits 2
     * @rdbLogicalType DECIMAL 
     */
    private double SSMOIN;

    /**
     * SOLDE RESTANT A SAISIR
     * @rdbPhysicalName SSSOIN
     * @rdbNotNull
     * @rdbSize 11
     * @rdbDigits 2
     * @rdbLogicalType DECIMAL 
     */
    private double SSSOIN;

    /**
     * Plafond mensuel saisie légale ouvrier
     * @rdbPhysicalName SSPLIN
     * @rdbNotNull
     * @rdbSize 9
     * @rdbDigits 2
     * @rdbLogicalType DECIMAL 
     */
    private double SSPLIN;

    /**
     * Plafond mensuel saisie employé
     * @rdbPhysicalName SSPEIN
     * @rdbNotNull
     * @rdbSize 9
     * @rdbDigits 2
     * @rdbLogicalType DECIMAL 
     */
    private double SSPEIN;

    /**
     * CODE SUSPENSION DES SAISIES
     * @rdbPhysicalName SSSSIN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String SSSSIN;

    /**
     * Catégorie interimaire
     * @rdbPhysicalName CATIIN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CATIIN;

    /**
     * Code activité avant Adia
     * @rdbPhysicalName AAVAIN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String AAVAIN;

    /**
     * Code publicité
     * @rdbPhysicalName CPUBIN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CPUBIN;

    /**
     * Code Education
     * @rdbPhysicalName CEDCIN
     * @rdbNotNull
     * @rdbSize 2
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double CEDCIN;

    /**
     * SIECLE
     * @rdbPhysicalName SSORIN
     * @rdbNotNull
     * @rdbSize 2
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double SSORIN;

    /**
     * Date de sortie
     * @rdbPhysicalName DSORIN
     * @rdbNotNull
     * @rdbSize 8
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double DSORIN;

    /**
     * Code motif départ
     * @rdbPhysicalName CDEPIN
     * @rdbNotNull
     * @rdbSize 2
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double CDEPIN;

    /**
     * Code allocataire
     * @rdbPhysicalName FACDIN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double FACDIN;

    /**
     * numero d' allocataire
     * @rdbPhysicalName NALFIN
     * @rdbNotNull
     * @rdbSize 10
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String NALFIN;

    /**
     * Nom de la mutuelle
     * @rdbPhysicalName NOMMIN
     * @rdbNotNull
     * @rdbSize 25
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String NOMMIN;

    /**
     * Numéro d'affiliation à la mutuelle
     * @rdbPhysicalName NAFMIN
     * @rdbNotNull
     * @rdbSize 15
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String NAFMIN;

    /**
     * Numéro de pension
     * @rdbPhysicalName NPENIN
     * @rdbNotNull
     * @rdbSize 10
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String NPENIN;

    /**
     * Dernier solde intérimaire
     * @rdbPhysicalName DSOLIN
     * @rdbNotNull
     * @rdbSize 11
     * @rdbDigits 2
     * @rdbLogicalType DECIMAL 
     */
    private double DSOLIN;

    /**
     * Partie du solde déja déduitedes acomptes
     * @rdbPhysicalName DSODIN
     * @rdbNotNull
     * @rdbSize 11
     * @rdbDigits 2
     * @rdbLogicalType DECIMAL 
     */
    private double DSODIN;

    /**
     * SIS card number
     * @rdbPhysicalName SSNRIN
     * @rdbNotNull
     * @rdbSize 10
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double SSNRIN;

    /**
     * SIS issue date
     * @rdbPhysicalName SSISIN
     * @rdbNotNull
     * @rdbSize 8
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double SSISIN;

    /**
     * SIS valid from date
     * @rdbPhysicalName SSVFIN
     * @rdbNotNull
     * @rdbSize 8
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double SSVFIN;

    /**
     * SIS valid to date
     * @rdbPhysicalName SSVTIN
     * @rdbNotNull
     * @rdbSize 8
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double SSVTIN;

    /**
     * SIS last update date
     * @rdbPhysicalName SSLDIN
     * @rdbNotNull
     * @rdbSize 8
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double SSLDIN;

    /**
     * SIS last update time
     * @rdbPhysicalName SSLTIN
     * @rdbNotNull
     * @rdbSize 6
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double SSLTIN;

    /**
     * Currency code
     * @rdbPhysicalName CURCIN
     * @rdbNotNull
     * @rdbSize 3
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CURCIN;

    /**
     * Status of the temp in MAX
     * @rdbPhysicalName TSTSIN
     * @rdbNotNull
     * @rdbSize 3
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String TSTSIN;

    /**
     * First Mission Date
     * @rdbPhysicalName FMDTIN
     * @rdbNotNull
     * @rdbSize 8
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double FMDTIN;

    /**
     * Creation Date in Max
     * @rdbPhysicalName CRDXIN
     * @rdbNotNull
     * @rdbSize 8
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double CRDXIN;

    /**
     * Change Date in Max
     * @rdbPhysicalName CHDXIN
     * @rdbNotNull
     * @rdbSize 8
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double CHDXIN;

    /**
     * CAN-PUBn (Max)
     * @rdbPhysicalName CP01IN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CP01IN;

    /**
     * CAN-PUBn (Max)
     * @rdbPhysicalName CP02IN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CP02IN;

    /**
     * CAN-PUBn (Max)
     * @rdbPhysicalName CP03IN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CP03IN;

    /**
     * CAN-PUBn (Max)
     * @rdbPhysicalName CP04IN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CP04IN;

    /**
     * CAN-PUBn (Max)
     * @rdbPhysicalName CP05IN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CP05IN;

    /**
     * CAN-PUBn (Max)
     * @rdbPhysicalName CP06IN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CP06IN;

    /**
     * CAN-PUBn (Max)
     * @rdbPhysicalName CP07IN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CP07IN;

    /**
     * CAN-PUBn (Max)
     * @rdbPhysicalName CP08IN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CP08IN;

    /**
     * CAN-PUBn (Max)
     * @rdbPhysicalName CP09IN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CP09IN;

    /**
     * CAN-PUBn (Max)
     * @rdbPhysicalName CP10IN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CP10IN;

    /**
     * CAN-PUBn (Max)
     * @rdbPhysicalName CP11IN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CP11IN;

    /**
     * CAN-PUBn (Max)
     * @rdbPhysicalName CP12IN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CP12IN;

    /**
     * CAN-PUBn (Max)
     * @rdbPhysicalName CP13IN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CP13IN;

    /**
     * CAN-PUBn (Max)
     * @rdbPhysicalName CP14IN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CP14IN;

    /**
     * CAN-PUBn (Max)
     * @rdbPhysicalName CP15IN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CP15IN;

    /**
     * CAN-PUBn (Max)
     * @rdbPhysicalName CP16IN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CP16IN;

    /**
     * CAN-PUBn (Max)
     * @rdbPhysicalName CP17IN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CP17IN;

    /**
     * CAN-PUBn (Max)
     * @rdbPhysicalName CP18IN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CP18IN;

    /**
     * CAN-PUBn (Max)
     * @rdbPhysicalName CP19IN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CP19IN;

    /**
     * CAN-PUBn (Max)
     * @rdbPhysicalName CP20IN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CP20IN;

    /**
     * CAN-PUBn (Max)
     * @rdbPhysicalName CP21IN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CP21IN;

    /**
     * CAN-PUBn (Max)
     * @rdbPhysicalName CP22IN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CP22IN;

    /**
     * CAN-PUBn (Max)
     * @rdbPhysicalName CP23IN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CP23IN;

    /**
     * CAN-PUBn (Max)
     * @rdbPhysicalName CP24IN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CP24IN;

    /**
     * CAN-PUBn (Max)
     * @rdbPhysicalName CP25IN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CP25IN;

    /**
     * CAN-PUBn (Max)
     * @rdbPhysicalName CP26IN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CP26IN;

    /**
     * CAN-PUBn (Max)
     * @rdbPhysicalName CP27IN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CP27IN;

    /**
     * CAN-PUBn (Max)
     * @rdbPhysicalName CP28IN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CP28IN;

    /**
     * CAN-PUBn (Max)
     * @rdbPhysicalName CP29IN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CP29IN;

    /**
     * CAN-PUBn (Max)
     * @rdbPhysicalName CP30IN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CP30IN;

    /**
     * Treat code for documents
     * @rdbPhysicalName TREAIN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String TREAIN;

    /**
     * Treat code Holiday Document
     * @rdbPhysicalName TRHLIN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String TRHLIN;

    /**
     * Unpaid Amount
     * @rdbPhysicalName UNPAIN
     * @rdbNotNull
     * @rdbSize 15
     * @rdbDigits 6
     * @rdbLogicalType DECIMAL 
     */
    private double UNPAIN;

    /**
     * No of children for saisies
     * @rdbPhysicalName CHI1IN
     * @rdbNotNull
     * @rdbSize 3
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL 
     */
    private double CHI1IN;

    /**
     * Primary Profession Id.
     * @rdbPhysicalName PROFIN
     * @rdbNotNull
     * @rdbSize 5
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL 
     */
    private double PROFIN;

    /**
     * Customer Id.Max Payroller
     * @rdbPhysicalName PAYNIN
     * @rdbNotNull
     * @rdbSize 6
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL 
     */
    private double PAYNIN;

    /**
     * Customer nbr for payroller
     * @rdbPhysicalName CNPAIN
     * @rdbNotNull
     * @rdbSize 9
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL 
     */
    private double CNPAIN;

    /**
     * RSZ nbr for payroller
     * @rdbPhysicalName RSZPIN
     * @rdbNotNull
     * @rdbSize 9
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL 
     */
    private double RSZPIN;

    /**
     * VAT nbr for payroller
     * @rdbPhysicalName VATPIN
     * @rdbNotNull
     * @rdbSize 9
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL 
     */
    private double VATPIN;

    /**
     * Invoeg Interim Start Date
     * @rdbPhysicalName IISTIN
     * @rdbNotNull
     * @rdbSize 8
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL 
     */
    private double IISTIN;

    /**
     * Invoeg Interim End Date
     * @rdbPhysicalName IIENIN
     * @rdbNotNull
     * @rdbSize 8
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL 
     */
    private double IIENIN;

    /**
     * Inv.Int.Branch Off./district
     * @rdbPhysicalName IIBRIN
     * @rdbNotNull
     * @rdbSize 3
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL 
     */
    private double IIBRIN;

    /**
     * BROF Last Time Sheet Max
     * @rdbPhysicalName BRTSIN
     * @rdbNotNull
     * @rdbSize 3
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double BRTSIN;

    /**
     * Date last contract Blue Coll
     * @rdbPhysicalName DTBCIN
     * @rdbNotNull
     * @rdbSize 8
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL 
     */
    private double DTBCIN;

    /**
     * Date last contract White Col
     * @rdbPhysicalName DTWCIN
     * @rdbNotNull
     * @rdbSize 8
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL 
     */
    private double DTWCIN;

    /**
     * %TAX to use by payroll
     * @rdbPhysicalName PCTXIN
     * @rdbNotNull
     * @rdbSize 5
     * @rdbDigits 2
     * @rdbLogicalType DECIMAL 
     */
    private double PCTXIN;

    /**
     * Balance last Payroll run
     * @rdbPhysicalName BALPIN
     * @rdbNotNull
     * @rdbSize 11
     * @rdbDigits 2
     * @rdbLogicalType DECIMAL 
     */
    private double BALPIN;

    /**
     * Balance previous Payroll run
     * @rdbPhysicalName BAPPIN
     * @rdbNotNull
     * @rdbSize 11
     * @rdbDigits 2
     * @rdbLogicalType DECIMAL 
     */
    private double BAPPIN;

    /**
     * Held for payment ?
     * @rdbPhysicalName PPHLIN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String PPHLIN;

    /**
     * Held for payroll ?
     * @rdbPhysicalName PYHLIN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String PYHLIN;

    /**
     * Risk category 1
     * @rdbPhysicalName RCA1IN
     * @rdbNotNull
     * @rdbSize 3
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double RCA1IN;

    /**
     * Risk category 2
     * @rdbPhysicalName RCA2IN
     * @rdbNotNull
     * @rdbSize 3
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double RCA2IN;

    /**
     * Follow up status premie
     * @rdbPhysicalName PREMIN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String PREMIN;

    /**
     * Indicator seizure limit
     * @rdbPhysicalName SZRLIN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String SZRLIN;

    /**
     * Countrycode Domicile
     * @rdbPhysicalName YDOMIN
     * @rdbNotNull
     * @rdbSize 3
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL 
     */
    private double YDOMIN;

    /**
     * ZIPcode Domicile
     * @rdbPhysicalName ZDOMIN
     * @rdbNotNull
     * @rdbSize 10
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String ZDOMIN;

    /**
     * Countrycode Residence
     * @rdbPhysicalName YRESIN
     * @rdbNotNull
     * @rdbSize 3
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL 
     */
    private double YRESIN;

    /**
     * ZIPcode Residence
     * @rdbPhysicalName ZRESIN
     * @rdbNotNull
     * @rdbSize 10
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String ZRESIN;

    /**
     * Countrycode birthplace
     * @rdbPhysicalName YBIRIN
     * @rdbNotNull
     * @rdbSize 3
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL 
     */
    private double YBIRIN;

    /**
     * Countrycode Nationality
     * @rdbPhysicalName YNATIN
     * @rdbNotNull
     * @rdbSize 3
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL 
     */
    private double YNATIN;

    /**
     * Instruction date construct
     * @rdbPhysicalName INDTIN
     * @rdbNotNull
     * @rdbSize 8
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL 
     */
    private double INDTIN;

    /**
     * Salary at start
     * @rdbPhysicalName SYSTIN
     * @rdbNotNull
     * @rdbSize 9
     * @rdbDigits 4
     * @rdbLogicalType DECIMAL 
     */
    private double SYSTIN;

    /**
     * Achterstallen Y/N
     * @rdbPhysicalName ACHTIN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String ACHTIN;

    /**
     * SSSOIN prev. payroll run
     * @rdbPhysicalName SZPPIN
     * @rdbNotNull
     * @rdbSize 11
     * @rdbDigits 2
     * @rdbLogicalType DECIMAL 
     */
    private double SZPPIN;

    /**
     * Changes in wage seizures
     * @rdbPhysicalName CHGZIN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CHGZIN;

    /**
     * Branch Office MC transfer to
     * @rdbPhysicalName BRMCIN
     * @rdbNotNull
     * @rdbSize 3
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL 
     */
    private double BRMCIN;

    /**
     * Date from Wage Seizure Easyp
     * @rdbPhysicalName DTSZIN
     * @rdbNotNull
     * @rdbSize 8
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL 
     */
    private double DTSZIN;

    /**
     * Recruitment medium
     * @rdbPhysicalName RECRIN
     * @rdbNotNull
     * @rdbSize 3
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL 
     */
    private double RECRIN;

    /**
     * Year Schoolverlater
     * @rdbPhysicalName YRSVIN
     * @rdbNotNull
     * @rdbSize 4
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL 
     */
    private double YRSVIN;

    /**
     * Account number foreign acct
     * @rdbPhysicalName EXBAIN
     * @rdbNotNull
     * @rdbSize 25
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String EXBAIN;

    /**
     * IBAN code
     * @rdbPhysicalName IBAN_IN
     * @rdbNotNull
     * @rdbSize 8
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String IBAN_IN;

    /**
     * BIC Bank identifier code
     * @rdbPhysicalName BIC_IN
     * @rdbNotNull
     * @rdbSize 11
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String BIC_IN;

    /**
     * Plan activa indicat. upfront
     * @rdbPhysicalName ACULIN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String ACULIN;

    /**
     * Plan Activa startdate upfrnt
     * @rdbPhysicalName ACSDIN
     * @rdbNotNull
     * @rdbSize 8
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL 
     */
    private double ACSDIN;

    /**
     * Date retired
     * @rdbPhysicalName RETDIN
     * @rdbNotNull
     * @rdbSize 8
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL 
     */
    private double RETDIN;

    /**
     * Reminders agreement
     * @rdbPhysicalName RMAGIN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String RMAGIN;

    /**
     * Agreement startdate
     * @rdbPhysicalName RMASIN
     * @rdbNotNull
     * @rdbSize 8
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL 
     */
    private double RMASIN;

    /**
     * Agreement amt back
     * @rdbPhysicalName RMAAIN
     * @rdbNotNull
     * @rdbSize 7
     * @rdbDigits 2
     * @rdbLogicalType DECIMAL 
     */
    private double RMAAIN;

    /**
     * Profile id
     * @rdbPhysicalName PRIDIN
     * @rdbNotNull
     * @rdbSize 6
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL 
     */
    private double PRIDIN;

    /**
     * Main profession
     * @rdbPhysicalName MNPRIN
     * @rdbNotNull
     * @rdbSize 5
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL 
     */
    private double MNPRIN;

    /**
     * Pay tax(BV) to foreign ctry
     * @rdbPhysicalName TXFOIN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String TXFOIN;

    /**
     * 1st subscription branch off.
     * @rdbPhysicalName SUBBIN
     * @rdbNotNull
     * @rdbSize 3
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double SUBBIN;

    /**
     * 1st subscription date
     * @rdbPhysicalName SUBDIN
     * @rdbNotNull
     * @rdbSize 8
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL 
     */
    private double SUBDIN;

    /**
     * 1st candidate branch off.
     * @rdbPhysicalName CANBIN
     * @rdbNotNull
     * @rdbSize 3
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double CANBIN;

    /**
     * 1st candidate date
     * @rdbPhysicalName CANDIN
     * @rdbNotNull
     * @rdbSize 8
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL 
     */
    private double CANDIN;

    /**
     * Lead passing end date
     * @rdbPhysicalName LPEDIN
     * @rdbNotNull
     * @rdbSize 8
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL 
     */
    private double LPEDIN;

    /**
     * VW-Personnel Register Number
     * @rdbPhysicalName PREGIN
     * @rdbNotNull
     * @rdbSize 7
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String PREGIN;

    /**
     * VW-Team code
     * @rdbPhysicalName TEAMIN
     * @rdbNotNull
     * @rdbSize 11
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String TEAMIN;

    /**
     * VW-Distribution point
     * @rdbPhysicalName DPNTIN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String DPNTIN;

    /**
     * VW-Shift
     * @rdbPhysicalName SHFTIN
     * @rdbNotNull
     * @rdbSize 2
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String SHFTIN;

    /**
     * Pay Slip document type
     * @rdbPhysicalName PSDOCTYPIN
     * @rdbNotNull
     * @rdbSize 2
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String PSDOCTYPIN;

    /**
     * Handicap Y/N
     * @rdbPhysicalName HANDICAPIN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String HANDICAPIN;

    /**
     * Fund (Handicap)
     * @rdbPhysicalName FUNDIN
     * @rdbNotNull
     * @rdbSize 3
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String FUNDIN;

    /**
     * Admission Number
     * @rdbPhysicalName ADMISSNRIN
     * @rdbNotNull
     * @rdbSize 6
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String ADMISSNRIN;

    /**
     * Handicap Date From
     * @rdbPhysicalName HANDDTFRIN
     * @rdbNotNull
     * @rdbSize 8
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL 
     */
    private double HANDDTFRIN;

    /**
     * Année de création du solde
     * @rdbPhysicalName DSOAIN
     * @rdbNotNull
     * @rdbSize 4
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double DSOAIN;

    /**
     * Période de création du solde
     * @rdbPhysicalName DSOPIN
     * @rdbNotNull
     * @rdbSize 2
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double DSOPIN;

    /**
     * Code solde a reporter
     * @rdbPhysicalName RSOLIN
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String RSOLIN;

    /**
     * succursale d' inscription
     * @rdbPhysicalName SUCIIN
     * @rdbNotNull
     * @rdbSize 3
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double SUCIIN;

    /**
     * Nationaal nummer Nederland
     * @rdbPhysicalName NEDNATIN
     * @rdbNotNull
     * @rdbSize 9
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL 
     */
    private double NEDNATIN;

    /**
     * Siècle de l'introduction / modification
     * @rdbPhysicalName SINTIN
     * @rdbNotNull
     * @rdbSize 2
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double SINTIN;

    /**
     * Creation or last change date
     * @rdbPhysicalName DINTIN
     * @rdbNotNull
     * @rdbSize 8
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double DINTIN;

    /**
     * Identité de l'opératrice
     * @rdbPhysicalName IDENIN
     * @rdbNotNull
     * @rdbSize 10
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String IDENIN;

    /**
     * IDENTITE OPR
     * @rdbPhysicalName MINVITIN
     * @rdbNotNull
     * @rdbSize 3
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double MINVITIN;
	/**
	 * @return
	 */
	public String getAAVAIN() {
		return AAVAIN;
	}

	/**
	 * @return
	 */
	public double getACAPIN() {
		return ACAPIN;
	}

	/**
	 * @return
	 */
	public String getACCNIN() {
		return ACCNIN;
	}

	/**
	 * @return
	 */
	public double getACENIN() {
		return ACENIN;
	}

	/**
	 * @return
	 */
	public String getACHTIN() {
		return ACHTIN;
	}

	/**
	 * @return
	 */
	public double getACSDIN() {
		return ACSDIN;
	}

	/**
	 * @return
	 */
	public String getACULIN() {
		return ACULIN;
	}

	/**
	 * @return
	 */
	public String getADMISSNRIN() {
		return ADMISSNRIN;
	}

	/**
	 * @return
	 */
	public String getADOKIN() {
		return ADOKIN;
	}

	/**
	 * @return
	 */
	public String getADRBIN() {
		return ADRBIN;
	}

	/**
	 * @return
	 */
	public String getADRDIN() {
		return ADRDIN;
	}

	/**
	 * @return
	 */
	public String getADRKIN() {
		return ADRKIN;
	}

	/**
	 * @return
	 */
	public String getADRRIN() {
		return ADRRIN;
	}

	/**
	 * @return
	 */
	public double getBALPIN() {
		return BALPIN;
	}

	/**
	 * @return
	 */
	public double getBAPPIN() {
		return BAPPIN;
	}

	/**
	 * @return
	 */
	public String getBIC_IN() {
		return BIC_IN;
	}

	/**
	 * @return
	 */
	public double getBRMCIN() {
		return BRMCIN;
	}

	/**
	 * @return
	 */
	public double getBRTSIN() {
		return BRTSIN;
	}

	/**
	 * @return
	 */
	public double getCANBIN() {
		return CANBIN;
	}

	/**
	 * @return
	 */
	public double getCANDIN() {
		return CANDIN;
	}

	/**
	 * @return
	 */
	public String getCATIIN() {
		return CATIIN;
	}

	/**
	 * @return
	 */
	public String getCCEMIN() {
		return CCEMIN;
	}

	/**
	 * @return
	 */
	public String getCCETIN() {
		return CCETIN;
	}

	/**
	 * @return
	 */
	public String getCCIBIN() {
		return CCIBIN;
	}

	/**
	 * @return
	 */
	public String getCCIVIN() {
		return CCIVIN;
	}

	/**
	 * @return
	 */
	public double getCDEPIN() {
		return CDEPIN;
	}

	/**
	 * @return
	 */
	public String getCDOSIN() {
		return CDOSIN;
	}

	/**
	 * @return
	 */
	public double getCEDCIN() {
		return CEDCIN;
	}

	/**
	 * @return
	 */
	public String getCEMLIN() {
		return CEMLIN;
	}

	/**
	 * @return
	 */
	public String getCETCIN() {
		return CETCIN;
	}

	/**
	 * @return
	 */
	public String getCETUIN() {
		return CETUIN;
	}

	/**
	 * @return
	 */
	public double getCHDXIN() {
		return CHDXIN;
	}

	/**
	 * @return
	 */
	public String getCHGZIN() {
		return CHGZIN;
	}

	/**
	 * @return
	 */
	public double getCHI1IN() {
		return CHI1IN;
	}

	/**
	 * @return
	 */
	public String getCINAIN() {
		return CINAIN;
	}

	/**
	 * @return
	 */
	public String getCLANIN() {
		return CLANIN;
	}

	/**
	 * @return
	 */
	public String getCNATIN() {
		return CNATIN;
	}

	/**
	 * @return
	 */
	public double getCNPAIN() {
		return CNPAIN;
	}

	/**
	 * @return
	 */
	public String getCOREIN() {
		return COREIN;
	}

	/**
	 * @return
	 */
	public String getCOUVIN() {
		return COUVIN;
	}

	/**
	 * @return
	 */
	public String getCP01IN() {
		return CP01IN;
	}

	/**
	 * @return
	 */
	public String getCP02IN() {
		return CP02IN;
	}

	/**
	 * @return
	 */
	public String getCP03IN() {
		return CP03IN;
	}

	/**
	 * @return
	 */
	public String getCP04IN() {
		return CP04IN;
	}

	/**
	 * @return
	 */
	public String getCP05IN() {
		return CP05IN;
	}

	/**
	 * @return
	 */
	public String getCP06IN() {
		return CP06IN;
	}

	/**
	 * @return
	 */
	public String getCP07IN() {
		return CP07IN;
	}

	/**
	 * @return
	 */
	public String getCP08IN() {
		return CP08IN;
	}

	/**
	 * @return
	 */
	public String getCP09IN() {
		return CP09IN;
	}

	/**
	 * @return
	 */
	public String getCP10IN() {
		return CP10IN;
	}

	/**
	 * @return
	 */
	public String getCP11IN() {
		return CP11IN;
	}

	/**
	 * @return
	 */
	public String getCP12IN() {
		return CP12IN;
	}

	/**
	 * @return
	 */
	public String getCP13IN() {
		return CP13IN;
	}

	/**
	 * @return
	 */
	public String getCP14IN() {
		return CP14IN;
	}

	/**
	 * @return
	 */
	public String getCP15IN() {
		return CP15IN;
	}

	/**
	 * @return
	 */
	public String getCP16IN() {
		return CP16IN;
	}

	/**
	 * @return
	 */
	public String getCP17IN() {
		return CP17IN;
	}

	/**
	 * @return
	 */
	public String getCP18IN() {
		return CP18IN;
	}

	/**
	 * @return
	 */
	public String getCP19IN() {
		return CP19IN;
	}

	/**
	 * @return
	 */
	public String getCP20IN() {
		return CP20IN;
	}

	/**
	 * @return
	 */
	public String getCP21IN() {
		return CP21IN;
	}

	/**
	 * @return
	 */
	public String getCP22IN() {
		return CP22IN;
	}

	/**
	 * @return
	 */
	public String getCP23IN() {
		return CP23IN;
	}

	/**
	 * @return
	 */
	public String getCP24IN() {
		return CP24IN;
	}

	/**
	 * @return
	 */
	public String getCP25IN() {
		return CP25IN;
	}

	/**
	 * @return
	 */
	public String getCP26IN() {
		return CP26IN;
	}

	/**
	 * @return
	 */
	public String getCP27IN() {
		return CP27IN;
	}

	/**
	 * @return
	 */
	public String getCP28IN() {
		return CP28IN;
	}

	/**
	 * @return
	 */
	public String getCP29IN() {
		return CP29IN;
	}

	/**
	 * @return
	 */
	public String getCP30IN() {
		return CP30IN;
	}

	/**
	 * @return
	 */
	public String getCPABIN() {
		return CPABIN;
	}

	/**
	 * @return
	 */
	public String getCPADIN() {
		return CPADIN;
	}

	/**
	 * @return
	 */
	public double getCPANIN() {
		return CPANIN;
	}

	/**
	 * @return
	 */
	public String getCPARIN() {
		return CPARIN;
	}

	/**
	 * @return
	 */
	public String getCPRCIN() {
		return CPRCIN;
	}

	/**
	 * @return
	 */
	public String getCPUBIN() {
		return CPUBIN;
	}

	/**
	 * @return
	 */
	public double getCRDXIN() {
		return CRDXIN;
	}

	/**
	 * @return
	 */
	public String getCSMAIN() {
		return CSMAIN;
	}

	/**
	 * @return
	 */
	public String getCSOSIN() {
		return CSOSIN;
	}

	/**
	 * @return
	 */
	public String getCTFRIN() {
		return CTFRIN;
	}

	/**
	 * @return
	 */
	public String getCURCIN() {
		return CURCIN;
	}

	/**
	 * @return
	 */
	public double getD1TRIN() {
		return D1TRIN;
	}

	/**
	 * @return
	 */
	public double getDDACIN() {
		return DDACIN;
	}

	/**
	 * @return
	 */
	public double getDDEFIN() {
		return DDEFIN;
	}

	/**
	 * @return
	 */
	public double getDENSIN() {
		return DENSIN;
	}

	/**
	 * @return
	 */
	public double getDFEFIN() {
		return DFEFIN;
	}

	/**
	 * @return
	 */
	public double getDINTIN() {
		return DINTIN;
	}

	/**
	 * @return
	 */
	public double getDNAIIN() {
		return DNAIIN;
	}

	/**
	 * @return
	 */
	public double getDNCNIN() {
		return DNCNIN;
	}

	/**
	 * @return
	 */
	public String getDPNTIN() {
		return DPNTIN;
	}

	/**
	 * @return
	 */
	public double getDSOAIN() {
		return DSOAIN;
	}

	/**
	 * @return
	 */
	public double getDSODIN() {
		return DSODIN;
	}

	/**
	 * @return
	 */
	public double getDSOLIN() {
		return DSOLIN;
	}

	/**
	 * @return
	 */
	public double getDSOPIN() {
		return DSOPIN;
	}

	/**
	 * @return
	 */
	public double getDSORIN() {
		return DSORIN;
	}

	/**
	 * @return
	 */
	public double getDTBCIN() {
		return DTBCIN;
	}

	/**
	 * @return
	 */
	public double getDTSZIN() {
		return DTSZIN;
	}

	/**
	 * @return
	 */
	public double getDTWCIN() {
		return DTWCIN;
	}

	/**
	 * @return
	 */
	public String getEXBAIN() {
		return EXBAIN;
	}

	/**
	 * @return
	 */
	public double getFACDIN() {
		return FACDIN;
	}

	/**
	 * @return
	 */
	public double getFMDTIN() {
		return FMDTIN;
	}

	/**
	 * @return
	 */
	public String getFUNDIN() {
		return FUNDIN;
	}

	/**
	 * @return
	 */
	public double getHANDDTFRIN() {
		return HANDDTFRIN;
	}

	/**
	 * @return
	 */
	public String getHANDICAPIN() {
		return HANDICAPIN;
	}

	/**
	 * @return
	 */
	public String getIBAN_IN() {
		return IBAN_IN;
	}

	/**
	 * @return
	 */
	public String getIDENIN() {
		return IDENIN;
	}

	/**
	 * @return
	 */
	public double getIIBRIN() {
		return IIBRIN;
	}

	/**
	 * @return
	 */
	public double getIIENIN() {
		return IIENIN;
	}

	/**
	 * @return
	 */
	public double getIISTIN() {
		return IISTIN;
	}

	/**
	 * @return
	 */
	public double getINDTIN() {
		return INDTIN;
	}

	/**
	 * @return
	 */
	public String getINITIN() {
		return INITIN;
	}

	/**
	 * @return
	 */
	public String getLNAIIN() {
		return LNAIIN;
	}

	/**
	 * @return
	 */
	public String getLOCBIN() {
		return LOCBIN;
	}

	/**
	 * @return
	 */
	public String getLOCDIN() {
		return LOCDIN;
	}

	/**
	 * @return
	 */
	public String getLOCRIN() {
		return LOCRIN;
	}

	/**
	 * @return
	 */
	public double getLPEDIN() {
		return LPEDIN;
	}

	/**
	 * @return
	 */
	public double getMINVITIN() {
		return MINVITIN;
	}

	/**
	 * @return
	 */
	public double getMNPRIN() {
		return MNPRIN;
	}

	/**
	 * @return
	 */
	public String getMODPIN() {
		return MODPIN;
	}

	/**
	 * @return
	 */
	public String getNAFMIN() {
		return NAFMIN;
	}

	/**
	 * @return
	 */
	public String getNALFIN() {
		return NALFIN;
	}

	/**
	 * @return
	 */
	public String getNBODIN() {
		return NBODIN;
	}

	/**
	 * @return
	 */
	public String getNBORIN() {
		return NBORIN;
	}

	/**
	 * @return
	 */
	public double getNCBNIN() {
		return NCBNIN;
	}

	/**
	 * @return
	 */
	public String getNCIDIN() {
		return NCIDIN;
	}

	/**
	 * @return
	 */
	public String getNCTRIN() {
		return NCTRIN;
	}

	/**
	 * @return
	 */
	public double getNEDNATIN() {
		return NEDNATIN;
	}

	/**
	 * @return
	 */
	public double getNINTIN() {
		return NINTIN;
	}

	/**
	 * @return
	 */
	public String getNMADIN() {
		return NMADIN;
	}

	/**
	 * @return
	 */
	public String getNMARIN() {
		return NMARIN;
	}

	/**
	 * @return
	 */
	public String getNOMBIN() {
		return NOMBIN;
	}

	/**
	 * @return
	 */
	public String getNOMEIN() {
		return NOMEIN;
	}

	/**
	 * @return
	 */
	public String getNOMIIN() {
		return NOMIIN;
	}

	/**
	 * @return
	 */
	public String getNOMMIN() {
		return NOMMIN;
	}

	/**
	 * @return
	 */
	public String getNPENIN() {
		return NPENIN;
	}

	/**
	 * @return
	 */
	public String getNPOBIN() {
		return NPOBIN;
	}

	/**
	 * @return
	 */
	public String getNPODIN() {
		return NPODIN;
	}

	/**
	 * @return
	 */
	public String getNPORIN() {
		return NPORIN;
	}

	/**
	 * @return
	 */
	public double getNRGNIN() {
		return NRGNIN;
	}

	/**
	 * @return
	 */
	public double getNSOCIN() {
		return NSOCIN;
	}

	/**
	 * @return
	 */
	public double getPAYNIN() {
		return PAYNIN;
	}

	/**
	 * @return
	 */
	public double getPCPRIN() {
		return PCPRIN;
	}

	/**
	 * @return
	 */
	public double getPCTXIN() {
		return PCTXIN;
	}

	/**
	 * @return
	 */
	public String getPHNRIN() {
		return PHNRIN;
	}

	/**
	 * @return
	 */
	public String getPHRRIN() {
		return PHRRIN;
	}

	/**
	 * @return
	 */
	public String getPPHLIN() {
		return PPHLIN;
	}

	/**
	 * @return
	 */
	public String getPREGIN() {
		return PREGIN;
	}

	/**
	 * @return
	 */
	public String getPREMIN() {
		return PREMIN;
	}

	/**
	 * @return
	 */
	public double getPRIDIN() {
		return PRIDIN;
	}

	/**
	 * @return
	 */
	public String getPRNMIN() {
		return PRNMIN;
	}

	/**
	 * @return
	 */
	public double getPROFIN() {
		return PROFIN;
	}

	/**
	 * @return
	 */
	public String getPSDOCTYPIN() {
		return PSDOCTYPIN;
	}

	/**
	 * @return
	 */
	public String getPYHLIN() {
		return PYHLIN;
	}

	/**
	 * @return
	 */
	public double getRCA1IN() {
		return RCA1IN;
	}

	/**
	 * @return
	 */
	public double getRCA2IN() {
		return RCA2IN;
	}

	/**
	 * @return
	 */
	public double getRECRIN() {
		return RECRIN;
	}

	/**
	 * @return
	 */
	public double getRETDIN() {
		return RETDIN;
	}

	/**
	 * @return
	 */
	public double getRMAAIN() {
		return RMAAIN;
	}

	/**
	 * @return
	 */
	public String getRMAGIN() {
		return RMAGIN;
	}

	/**
	 * @return
	 */
	public double getRMASIN() {
		return RMASIN;
	}

	/**
	 * @return
	 */
	public String getRSOLIN() {
		return RSOLIN;
	}

	/**
	 * @return
	 */
	public double getRSZPIN() {
		return RSZPIN;
	}

	/**
	 * @return
	 */
	public double getS1TRIN() {
		return S1TRIN;
	}

	/**
	 * @return
	 */
	public double getSDACIN() {
		return SDACIN;
	}

	/**
	 * @return
	 */
	public double getSDEFIN() {
		return SDEFIN;
	}

	/**
	 * @return
	 */
	public double getSENSIN() {
		return SENSIN;
	}

	/**
	 * @return
	 */
	public String getSEXEIN() {
		return SEXEIN;
	}

	/**
	 * @return
	 */
	public double getSFEFIN() {
		return SFEFIN;
	}

	/**
	 * @return
	 */
	public String getSHFTIN() {
		return SHFTIN;
	}

	/**
	 * @return
	 */
	public double getSINTIN() {
		return SINTIN;
	}

	/**
	 * @return
	 */
	public double getSNAIIN() {
		return SNAIIN;
	}

	/**
	 * @return
	 */
	public double getSSFEIN() {
		return SSFEIN;
	}

	/**
	 * @return
	 */
	public double getSSFOIN() {
		return SSFOIN;
	}

	/**
	 * @return
	 */
	public double getSSISIN() {
		return SSISIN;
	}

	/**
	 * @return
	 */
	public double getSSLDIN() {
		return SSLDIN;
	}

	/**
	 * @return
	 */
	public double getSSLTIN() {
		return SSLTIN;
	}

	/**
	 * @return
	 */
	public double getSSMOIN() {
		return SSMOIN;
	}

	/**
	 * @return
	 */
	public double getSSNRIN() {
		return SSNRIN;
	}

	/**
	 * @return
	 */
	public double getSSORIN() {
		return SSORIN;
	}

	/**
	 * @return
	 */
	public double getSSPEIN() {
		return SSPEIN;
	}

	/**
	 * @return
	 */
	public double getSSPLIN() {
		return SSPLIN;
	}

	/**
	 * @return
	 */
	public double getSSSOIN() {
		return SSSOIN;
	}

	/**
	 * @return
	 */
	public String getSSSSIN() {
		return SSSSIN;
	}

	/**
	 * @return
	 */
	public double getSSVFIN() {
		return SSVFIN;
	}

	/**
	 * @return
	 */
	public double getSSVTIN() {
		return SSVTIN;
	}

	/**
	 * @return
	 */
	public double getSUBBIN() {
		return SUBBIN;
	}

	/**
	 * @return
	 */
	public double getSUBDIN() {
		return SUBDIN;
	}

	/**
	 * @return
	 */
	public double getSUCGIN() {
		return SUCGIN;
	}

	/**
	 * @return
	 */
	public double getSUCIIN() {
		return SUCIIN;
	}

	/**
	 * @return
	 */
	public double getSYSTIN() {
		return SYSTIN;
	}

	/**
	 * @return
	 */
	public double getSZPPIN() {
		return SZPPIN;
	}

	/**
	 * @return
	 */
	public String getSZRLIN() {
		return SZRLIN;
	}

	/**
	 * @return
	 */
	public String getTCTRIN() {
		return TCTRIN;
	}

	/**
	 * @return
	 */
	public String getTDOIIN() {
		return TDOIIN;
	}

	/**
	 * @return
	 */
	public String getTEAMIN() {
		return TEAMIN;
	}

	/**
	 * @return
	 */
	public String getTREAIN() {
		return TREAIN;
	}

	/**
	 * @return
	 */
	public String getTRHLIN() {
		return TRHLIN;
	}

	/**
	 * @return
	 */
	public String getTSTSIN() {
		return TSTSIN;
	}

	/**
	 * @return
	 */
	public String getTXFOIN() {
		return TXFOIN;
	}

	/**
	 * @return
	 */
	public double getUNPAIN() {
		return UNPAIN;
	}

	/**
	 * @return
	 */
	public double getVATPIN() {
		return VATPIN;
	}

	/**
	 * @return
	 */
	public double getYBIRIN() {
		return YBIRIN;
	}

	/**
	 * @return
	 */
	public double getYDOMIN() {
		return YDOMIN;
	}

	/**
	 * @return
	 */
	public double getYNATIN() {
		return YNATIN;
	}

	/**
	 * @return
	 */
	public double getYRESIN() {
		return YRESIN;
	}

	/**
	 * @return
	 */
	public double getYRSVIN() {
		return YRSVIN;
	}

	/**
	 * @return
	 */
	public String getZDOMIN() {
		return ZDOMIN;
	}

	/**
	 * @return
	 */
	public String getZRESIN() {
		return ZRESIN;
	}

	/**
	 * @param string
	 */
	public void setAAVAIN(String string) {
		AAVAIN = string;
	}

	/**
	 * @param d
	 */
	public void setACAPIN(double d) {
		ACAPIN = d;
	}

	/**
	 * @param string
	 */
	public void setACCNIN(String string) {
		ACCNIN = string;
	}

	/**
	 * @param d
	 */
	public void setACENIN(double d) {
		ACENIN = d;
	}

	/**
	 * @param string
	 */
	public void setACHTIN(String string) {
		ACHTIN = string;
	}

	/**
	 * @param d
	 */
	public void setACSDIN(double d) {
		ACSDIN = d;
	}

	/**
	 * @param string
	 */
	public void setACULIN(String string) {
		ACULIN = string;
	}

	/**
	 * @param string
	 */
	public void setADMISSNRIN(String string) {
		ADMISSNRIN = string;
	}

	/**
	 * @param string
	 */
	public void setADOKIN(String string) {
		ADOKIN = string;
	}

	/**
	 * @param string
	 */
	public void setADRBIN(String string) {
		ADRBIN = string;
	}

	/**
	 * @param string
	 */
	public void setADRDIN(String string) {
		ADRDIN = string;
	}

	/**
	 * @param string
	 */
	public void setADRKIN(String string) {
		ADRKIN = string;
	}

	/**
	 * @param string
	 */
	public void setADRRIN(String string) {
		ADRRIN = string;
	}

	/**
	 * @param d
	 */
	public void setBALPIN(double d) {
		BALPIN = d;
	}

	/**
	 * @param d
	 */
	public void setBAPPIN(double d) {
		BAPPIN = d;
	}

	/**
	 * @param string
	 */
	public void setBIC_IN(String string) {
		BIC_IN = string;
	}

	/**
	 * @param d
	 */
	public void setBRMCIN(double d) {
		BRMCIN = d;
	}

	/**
	 * @param d
	 */
	public void setBRTSIN(double d) {
		BRTSIN = d;
	}

	/**
	 * @param d
	 */
	public void setCANBIN(double d) {
		CANBIN = d;
	}

	/**
	 * @param d
	 */
	public void setCANDIN(double d) {
		CANDIN = d;
	}

	/**
	 * @param string
	 */
	public void setCATIIN(String string) {
		CATIIN = string;
	}

	/**
	 * @param string
	 */
	public void setCCEMIN(String string) {
		CCEMIN = string;
	}

	/**
	 * @param string
	 */
	public void setCCETIN(String string) {
		CCETIN = string;
	}

	/**
	 * @param string
	 */
	public void setCCIBIN(String string) {
		CCIBIN = string;
	}

	/**
	 * @param string
	 */
	public void setCCIVIN(String string) {
		CCIVIN = string;
	}

	/**
	 * @param d
	 */
	public void setCDEPIN(double d) {
		CDEPIN = d;
	}

	/**
	 * @param string
	 */
	public void setCDOSIN(String string) {
		CDOSIN = string;
	}

	/**
	 * @param d
	 */
	public void setCEDCIN(double d) {
		CEDCIN = d;
	}

	/**
	 * @param string
	 */
	public void setCEMLIN(String string) {
		CEMLIN = string;
	}

	/**
	 * @param string
	 */
	public void setCETCIN(String string) {
		CETCIN = string;
	}

	/**
	 * @param string
	 */
	public void setCETUIN(String string) {
		CETUIN = string;
	}

	/**
	 * @param d
	 */
	public void setCHDXIN(double d) {
		CHDXIN = d;
	}

	/**
	 * @param string
	 */
	public void setCHGZIN(String string) {
		CHGZIN = string;
	}

	/**
	 * @param d
	 */
	public void setCHI1IN(double d) {
		CHI1IN = d;
	}

	/**
	 * @param string
	 */
	public void setCINAIN(String string) {
		CINAIN = string;
	}

	/**
	 * @param string
	 */
	public void setCLANIN(String string) {
		CLANIN = string;
	}

	/**
	 * @param string
	 */
	public void setCNATIN(String string) {
		CNATIN = string;
	}

	/**
	 * @param d
	 */
	public void setCNPAIN(double d) {
		CNPAIN = d;
	}

	/**
	 * @param string
	 */
	public void setCOREIN(String string) {
		COREIN = string;
	}

	/**
	 * @param string
	 */
	public void setCOUVIN(String string) {
		COUVIN = string;
	}

	/**
	 * @param string
	 */
	public void setCP01IN(String string) {
		CP01IN = string;
	}

	/**
	 * @param string
	 */
	public void setCP02IN(String string) {
		CP02IN = string;
	}

	/**
	 * @param string
	 */
	public void setCP03IN(String string) {
		CP03IN = string;
	}

	/**
	 * @param string
	 */
	public void setCP04IN(String string) {
		CP04IN = string;
	}

	/**
	 * @param string
	 */
	public void setCP05IN(String string) {
		CP05IN = string;
	}

	/**
	 * @param string
	 */
	public void setCP06IN(String string) {
		CP06IN = string;
	}

	/**
	 * @param string
	 */
	public void setCP07IN(String string) {
		CP07IN = string;
	}

	/**
	 * @param string
	 */
	public void setCP08IN(String string) {
		CP08IN = string;
	}

	/**
	 * @param string
	 */
	public void setCP09IN(String string) {
		CP09IN = string;
	}

	/**
	 * @param string
	 */
	public void setCP10IN(String string) {
		CP10IN = string;
	}

	/**
	 * @param string
	 */
	public void setCP11IN(String string) {
		CP11IN = string;
	}

	/**
	 * @param string
	 */
	public void setCP12IN(String string) {
		CP12IN = string;
	}

	/**
	 * @param string
	 */
	public void setCP13IN(String string) {
		CP13IN = string;
	}

	/**
	 * @param string
	 */
	public void setCP14IN(String string) {
		CP14IN = string;
	}

	/**
	 * @param string
	 */
	public void setCP15IN(String string) {
		CP15IN = string;
	}

	/**
	 * @param string
	 */
	public void setCP16IN(String string) {
		CP16IN = string;
	}

	/**
	 * @param string
	 */
	public void setCP17IN(String string) {
		CP17IN = string;
	}

	/**
	 * @param string
	 */
	public void setCP18IN(String string) {
		CP18IN = string;
	}

	/**
	 * @param string
	 */
	public void setCP19IN(String string) {
		CP19IN = string;
	}

	/**
	 * @param string
	 */
	public void setCP20IN(String string) {
		CP20IN = string;
	}

	/**
	 * @param string
	 */
	public void setCP21IN(String string) {
		CP21IN = string;
	}

	/**
	 * @param string
	 */
	public void setCP22IN(String string) {
		CP22IN = string;
	}

	/**
	 * @param string
	 */
	public void setCP23IN(String string) {
		CP23IN = string;
	}

	/**
	 * @param string
	 */
	public void setCP24IN(String string) {
		CP24IN = string;
	}

	/**
	 * @param string
	 */
	public void setCP25IN(String string) {
		CP25IN = string;
	}

	/**
	 * @param string
	 */
	public void setCP26IN(String string) {
		CP26IN = string;
	}

	/**
	 * @param string
	 */
	public void setCP27IN(String string) {
		CP27IN = string;
	}

	/**
	 * @param string
	 */
	public void setCP28IN(String string) {
		CP28IN = string;
	}

	/**
	 * @param string
	 */
	public void setCP29IN(String string) {
		CP29IN = string;
	}

	/**
	 * @param string
	 */
	public void setCP30IN(String string) {
		CP30IN = string;
	}

	/**
	 * @param string
	 */
	public void setCPABIN(String string) {
		CPABIN = string;
	}

	/**
	 * @param string
	 */
	public void setCPADIN(String string) {
		CPADIN = string;
	}

	/**
	 * @param d
	 */
	public void setCPANIN(double d) {
		CPANIN = d;
	}

	/**
	 * @param string
	 */
	public void setCPARIN(String string) {
		CPARIN = string;
	}

	/**
	 * @param string
	 */
	public void setCPRCIN(String string) {
		CPRCIN = string;
	}

	/**
	 * @param string
	 */
	public void setCPUBIN(String string) {
		CPUBIN = string;
	}

	/**
	 * @param d
	 */
	public void setCRDXIN(double d) {
		CRDXIN = d;
	}

	/**
	 * @param string
	 */
	public void setCSMAIN(String string) {
		CSMAIN = string;
	}

	/**
	 * @param string
	 */
	public void setCSOSIN(String string) {
		CSOSIN = string;
	}

	/**
	 * @param string
	 */
	public void setCTFRIN(String string) {
		CTFRIN = string;
	}

	/**
	 * @param string
	 */
	public void setCURCIN(String string) {
		CURCIN = string;
	}

	/**
	 * @param d
	 */
	public void setD1TRIN(double d) {
		D1TRIN = d;
	}

	/**
	 * @param d
	 */
	public void setDDACIN(double d) {
		DDACIN = d;
	}

	/**
	 * @param d
	 */
	public void setDDEFIN(double d) {
		DDEFIN = d;
	}

	/**
	 * @param d
	 */
	public void setDENSIN(double d) {
		DENSIN = d;
	}

	/**
	 * @param d
	 */
	public void setDFEFIN(double d) {
		DFEFIN = d;
	}

	/**
	 * @param d
	 */
	public void setDINTIN(double d) {
		DINTIN = d;
	}

	/**
	 * @param d
	 */
	public void setDNAIIN(double d) {
		DNAIIN = d;
	}

	/**
	 * @param d
	 */
	public void setDNCNIN(double d) {
		DNCNIN = d;
	}

	/**
	 * @param string
	 */
	public void setDPNTIN(String string) {
		DPNTIN = string;
	}

	/**
	 * @param d
	 */
	public void setDSOAIN(double d) {
		DSOAIN = d;
	}

	/**
	 * @param d
	 */
	public void setDSODIN(double d) {
		DSODIN = d;
	}

	/**
	 * @param d
	 */
	public void setDSOLIN(double d) {
		DSOLIN = d;
	}

	/**
	 * @param d
	 */
	public void setDSOPIN(double d) {
		DSOPIN = d;
	}

	/**
	 * @param d
	 */
	public void setDSORIN(double d) {
		DSORIN = d;
	}

	/**
	 * @param d
	 */
	public void setDTBCIN(double d) {
		DTBCIN = d;
	}

	/**
	 * @param d
	 */
	public void setDTSZIN(double d) {
		DTSZIN = d;
	}

	/**
	 * @param d
	 */
	public void setDTWCIN(double d) {
		DTWCIN = d;
	}

	/**
	 * @param string
	 */
	public void setEXBAIN(String string) {
		EXBAIN = string;
	}

	/**
	 * @param d
	 */
	public void setFACDIN(double d) {
		FACDIN = d;
	}

	/**
	 * @param d
	 */
	public void setFMDTIN(double d) {
		FMDTIN = d;
	}

	/**
	 * @param string
	 */
	public void setFUNDIN(String string) {
		FUNDIN = string;
	}

	/**
	 * @param d
	 */
	public void setHANDDTFRIN(double d) {
		HANDDTFRIN = d;
	}

	/**
	 * @param string
	 */
	public void setHANDICAPIN(String string) {
		HANDICAPIN = string;
	}

	/**
	 * @param string
	 */
	public void setIBAN_IN(String string) {
		IBAN_IN = string;
	}

	/**
	 * @param string
	 */
	public void setIDENIN(String string) {
		IDENIN = string;
	}

	/**
	 * @param d
	 */
	public void setIIBRIN(double d) {
		IIBRIN = d;
	}

	/**
	 * @param d
	 */
	public void setIIENIN(double d) {
		IIENIN = d;
	}

	/**
	 * @param d
	 */
	public void setIISTIN(double d) {
		IISTIN = d;
	}

	/**
	 * @param d
	 */
	public void setINDTIN(double d) {
		INDTIN = d;
	}

	/**
	 * @param string
	 */
	public void setINITIN(String string) {
		INITIN = string;
	}

	/**
	 * @param string
	 */
	public void setLNAIIN(String string) {
		LNAIIN = string;
	}

	/**
	 * @param string
	 */
	public void setLOCBIN(String string) {
		LOCBIN = string;
	}

	/**
	 * @param string
	 */
	public void setLOCDIN(String string) {
		LOCDIN = string;
	}

	/**
	 * @param string
	 */
	public void setLOCRIN(String string) {
		LOCRIN = string;
	}

	/**
	 * @param d
	 */
	public void setLPEDIN(double d) {
		LPEDIN = d;
	}

	/**
	 * @param d
	 */
	public void setMINVITIN(double d) {
		MINVITIN = d;
	}

	/**
	 * @param d
	 */
	public void setMNPRIN(double d) {
		MNPRIN = d;
	}

	/**
	 * @param string
	 */
	public void setMODPIN(String string) {
		MODPIN = string;
	}

	/**
	 * @param string
	 */
	public void setNAFMIN(String string) {
		NAFMIN = string;
	}

	/**
	 * @param string
	 */
	public void setNALFIN(String string) {
		NALFIN = string;
	}

	/**
	 * @param string
	 */
	public void setNBODIN(String string) {
		NBODIN = string;
	}

	/**
	 * @param string
	 */
	public void setNBORIN(String string) {
		NBORIN = string;
	}

	/**
	 * @param d
	 */
	public void setNCBNIN(double d) {
		NCBNIN = d;
	}

	/**
	 * @param string
	 */
	public void setNCIDIN(String string) {
		NCIDIN = string;
	}

	/**
	 * @param string
	 */
	public void setNCTRIN(String string) {
		NCTRIN = string;
	}

	/**
	 * @param d
	 */
	public void setNEDNATIN(double d) {
		NEDNATIN = d;
	}

	/**
	 * @param d
	 */
	public void setNINTIN(double d) {
		NINTIN = d;
	}

	/**
	 * @param string
	 */
	public void setNMADIN(String string) {
		NMADIN = string;
	}

	/**
	 * @param string
	 */
	public void setNMARIN(String string) {
		NMARIN = string;
	}

	/**
	 * @param string
	 */
	public void setNOMBIN(String string) {
		NOMBIN = string;
	}

	/**
	 * @param string
	 */
	public void setNOMEIN(String string) {
		NOMEIN = string;
	}

	/**
	 * @param string
	 */
	public void setNOMIIN(String string) {
		NOMIIN = string;
	}

	/**
	 * @param string
	 */
	public void setNOMMIN(String string) {
		NOMMIN = string;
	}

	/**
	 * @param string
	 */
	public void setNPENIN(String string) {
		NPENIN = string;
	}

	/**
	 * @param string
	 */
	public void setNPOBIN(String string) {
		NPOBIN = string;
	}

	/**
	 * @param string
	 */
	public void setNPODIN(String string) {
		NPODIN = string;
	}

	/**
	 * @param string
	 */
	public void setNPORIN(String string) {
		NPORIN = string;
	}

	/**
	 * @param d
	 */
	public void setNRGNIN(double d) {
		NRGNIN = d;
	}

	/**
	 * @param d
	 */
	public void setNSOCIN(double d) {
		NSOCIN = d;
	}

	/**
	 * @param d
	 */
	public void setPAYNIN(double d) {
		PAYNIN = d;
	}

	/**
	 * @param d
	 */
	public void setPCPRIN(double d) {
		PCPRIN = d;
	}

	/**
	 * @param d
	 */
	public void setPCTXIN(double d) {
		PCTXIN = d;
	}

	/**
	 * @param string
	 */
	public void setPHNRIN(String string) {
		PHNRIN = string;
	}

	/**
	 * @param string
	 */
	public void setPHRRIN(String string) {
		PHRRIN = string;
	}

	/**
	 * @param string
	 */
	public void setPPHLIN(String string) {
		PPHLIN = string;
	}

	/**
	 * @param string
	 */
	public void setPREGIN(String string) {
		PREGIN = string;
	}

	/**
	 * @param string
	 */
	public void setPREMIN(String string) {
		PREMIN = string;
	}

	/**
	 * @param d
	 */
	public void setPRIDIN(double d) {
		PRIDIN = d;
	}

	/**
	 * @param string
	 */
	public void setPRNMIN(String string) {
		PRNMIN = string;
	}

	/**
	 * @param d
	 */
	public void setPROFIN(double d) {
		PROFIN = d;
	}

	/**
	 * @param string
	 */
	public void setPSDOCTYPIN(String string) {
		PSDOCTYPIN = string;
	}

	/**
	 * @param string
	 */
	public void setPYHLIN(String string) {
		PYHLIN = string;
	}

	/**
	 * @param d
	 */
	public void setRCA1IN(double d) {
		RCA1IN = d;
	}

	/**
	 * @param d
	 */
	public void setRCA2IN(double d) {
		RCA2IN = d;
	}

	/**
	 * @param d
	 */
	public void setRECRIN(double d) {
		RECRIN = d;
	}

	/**
	 * @param d
	 */
	public void setRETDIN(double d) {
		RETDIN = d;
	}

	/**
	 * @param d
	 */
	public void setRMAAIN(double d) {
		RMAAIN = d;
	}

	/**
	 * @param string
	 */
	public void setRMAGIN(String string) {
		RMAGIN = string;
	}

	/**
	 * @param d
	 */
	public void setRMASIN(double d) {
		RMASIN = d;
	}

	/**
	 * @param string
	 */
	public void setRSOLIN(String string) {
		RSOLIN = string;
	}

	/**
	 * @param d
	 */
	public void setRSZPIN(double d) {
		RSZPIN = d;
	}

	/**
	 * @param d
	 */
	public void setS1TRIN(double d) {
		S1TRIN = d;
	}

	/**
	 * @param d
	 */
	public void setSDACIN(double d) {
		SDACIN = d;
	}

	/**
	 * @param d
	 */
	public void setSDEFIN(double d) {
		SDEFIN = d;
	}

	/**
	 * @param d
	 */
	public void setSENSIN(double d) {
		SENSIN = d;
	}

	/**
	 * @param string
	 */
	public void setSEXEIN(String string) {
		SEXEIN = string;
	}

	/**
	 * @param d
	 */
	public void setSFEFIN(double d) {
		SFEFIN = d;
	}

	/**
	 * @param string
	 */
	public void setSHFTIN(String string) {
		SHFTIN = string;
	}

	/**
	 * @param d
	 */
	public void setSINTIN(double d) {
		SINTIN = d;
	}

	/**
	 * @param d
	 */
	public void setSNAIIN(double d) {
		SNAIIN = d;
	}

	/**
	 * @param d
	 */
	public void setSSFEIN(double d) {
		SSFEIN = d;
	}

	/**
	 * @param d
	 */
	public void setSSFOIN(double d) {
		SSFOIN = d;
	}

	/**
	 * @param d
	 */
	public void setSSISIN(double d) {
		SSISIN = d;
	}

	/**
	 * @param d
	 */
	public void setSSLDIN(double d) {
		SSLDIN = d;
	}

	/**
	 * @param d
	 */
	public void setSSLTIN(double d) {
		SSLTIN = d;
	}

	/**
	 * @param d
	 */
	public void setSSMOIN(double d) {
		SSMOIN = d;
	}

	/**
	 * @param d
	 */
	public void setSSNRIN(double d) {
		SSNRIN = d;
	}

	/**
	 * @param d
	 */
	public void setSSORIN(double d) {
		SSORIN = d;
	}

	/**
	 * @param d
	 */
	public void setSSPEIN(double d) {
		SSPEIN = d;
	}

	/**
	 * @param d
	 */
	public void setSSPLIN(double d) {
		SSPLIN = d;
	}

	/**
	 * @param d
	 */
	public void setSSSOIN(double d) {
		SSSOIN = d;
	}

	/**
	 * @param string
	 */
	public void setSSSSIN(String string) {
		SSSSIN = string;
	}

	/**
	 * @param d
	 */
	public void setSSVFIN(double d) {
		SSVFIN = d;
	}

	/**
	 * @param d
	 */
	public void setSSVTIN(double d) {
		SSVTIN = d;
	}

	/**
	 * @param d
	 */
	public void setSUBBIN(double d) {
		SUBBIN = d;
	}

	/**
	 * @param d
	 */
	public void setSUBDIN(double d) {
		SUBDIN = d;
	}

	/**
	 * @param d
	 */
	public void setSUCGIN(double d) {
		SUCGIN = d;
	}

	/**
	 * @param d
	 */
	public void setSUCIIN(double d) {
		SUCIIN = d;
	}

	/**
	 * @param d
	 */
	public void setSYSTIN(double d) {
		SYSTIN = d;
	}

	/**
	 * @param d
	 */
	public void setSZPPIN(double d) {
		SZPPIN = d;
	}

	/**
	 * @param string
	 */
	public void setSZRLIN(String string) {
		SZRLIN = string;
	}

	/**
	 * @param string
	 */
	public void setTCTRIN(String string) {
		TCTRIN = string;
	}

	/**
	 * @param string
	 */
	public void setTDOIIN(String string) {
		TDOIIN = string;
	}

	/**
	 * @param string
	 */
	public void setTEAMIN(String string) {
		TEAMIN = string;
	}

	/**
	 * @param string
	 */
	public void setTREAIN(String string) {
		TREAIN = string;
	}

	/**
	 * @param string
	 */
	public void setTRHLIN(String string) {
		TRHLIN = string;
	}

	/**
	 * @param string
	 */
	public void setTSTSIN(String string) {
		TSTSIN = string;
	}

	/**
	 * @param string
	 */
	public void setTXFOIN(String string) {
		TXFOIN = string;
	}

	/**
	 * @param d
	 */
	public void setUNPAIN(double d) {
		UNPAIN = d;
	}

	/**
	 * @param d
	 */
	public void setVATPIN(double d) {
		VATPIN = d;
	}

	/**
	 * @param d
	 */
	public void setYBIRIN(double d) {
		YBIRIN = d;
	}

	/**
	 * @param d
	 */
	public void setYDOMIN(double d) {
		YDOMIN = d;
	}

	/**
	 * @param d
	 */
	public void setYNATIN(double d) {
		YNATIN = d;
	}

	/**
	 * @param d
	 */
	public void setYRESIN(double d) {
		YRESIN = d;
	}

	/**
	 * @param d
	 */
	public void setYRSVIN(double d) {
		YRSVIN = d;
	}

	/**
	 * @param string
	 */
	public void setZDOMIN(String string) {
		ZDOMIN = string;
	}

	/**
	 * @param string
	 */
	public void setZRESIN(String string) {
		ZRESIN = string;
	}

}
