/* Generated by Together */

package database.datastore;

/**
 * @persistent
 * @rdbPhysicalName FSUMAS 
 */
public class FSUMAS {
    public FSUMAS() {
    }

    /**
     * Numéro société
     * @rdbPhysicalName NSOCSU
     * @rdbNotNull
     * @rdbSize 2
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double NSOCSU;

    /**
     * Numéro de succursale
     * @rdbPhysicalName SUCGSU
     * @rdbNotNull
     * @rdbSize 3
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double SUCGSU;

    /**
     * Numéro de la région
     * @rdbPhysicalName NREGSU
     * @rdbNotNull
     * @rdbSize 2
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double NREGSU;

    /**
     * Nom
     * @rdbPhysicalName LISUSU
     * @rdbNotNull
     * @rdbSize 25
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String LISUSU;

    /**
     * Name 50 positions
     * @rdbPhysicalName LONGNAMESU
     * @rdbNotNull
     * @rdbSize 50
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String LONGNAMESU;

    /**
     * Address (Street)
     * @rdbPhysicalName ADRDSU
     * @rdbNotNull
     * @rdbSize 40
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String ADRDSU;

    /**
     * Code pays du domicile
     * @rdbPhysicalName CPADSU
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CPADSU;

    /**
     * Numéro de la boîte postale
     * @rdbPhysicalName NBODSU
     * @rdbNotNull
     * @rdbSize 4
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String NBODSU;

    /**
     * Numéro du canton postal du domicile
     * @rdbPhysicalName NPODSU
     * @rdbNotNull
     * @rdbSize 6
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String NPODSU;

    /**
     * Localité du domicile
     * @rdbPhysicalName LOCDSU
     * @rdbNotNull
     * @rdbSize 25
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String LOCDSU;

    /**
     * Nom du responsable de la succursale
     * @rdbPhysicalName NOMRSU
     * @rdbNotNull
     * @rdbSize 30
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String NOMRSU;

    /**
     * Nom du responsable commercial
     * @rdbPhysicalName NOMCSU
     * @rdbNotNull
     * @rdbSize 30
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String NOMCSU;

    /**
     * Nom du responsable planning
     * @rdbPhysicalName NOMPSU
     * @rdbNotNull
     * @rdbSize 30
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String NOMPSU;

    /**
     * Numéro de téléphone
     * @rdbPhysicalName PHNRSU
     * @rdbNotNull
     * @rdbSize 15
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String PHNRSU;

    /**
     * Numéro de téléfax
     * @rdbPhysicalName FXNRSU
     * @rdbNotNull
     * @rdbSize 13
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL 
     */
    private double FXNRSU;

    /**
     * Code langue
     * @rdbPhysicalName CLANSU
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CLANSU;

    /**
     * Statut linguistique
     * @rdbPhysicalName SLANSU
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String SLANSU;

    /**
     * Société de consolidation
     * @rdbPhysicalName SOCCSU
     * @rdbNotNull
     * @rdbSize 2
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double SOCCSU;

    /**
     * Succursale de consol
     * @rdbPhysicalName SUCCSU
     * @rdbNotNull
     * @rdbSize 3
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double SUCCSU;

    /**
     * Dernier numéro de contrat utilisé
     * @rdbPhysicalName DNOCSU
     * @rdbNotNull
     * @rdbSize 5
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL 
     */
    private double DNOCSU;

    /**
     * District Code
     * @rdbPhysicalName DICDSU
     * @rdbNotNull
     * @rdbSize 3
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String DICDSU;

    /**
     * Office Mgr Code Obsolete!!!
     * @rdbPhysicalName OMCDSU
     * @rdbNotNull
     * @rdbSize 3
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String OMCDSU;

    /**
     * Branch office category code
     * @rdbPhysicalName BCCDSU
     * @rdbNotNull
     * @rdbSize 2
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double BCCDSU;

    /**
     * Branch office activity code
     * @rdbPhysicalName BACDSU
     * @rdbNotNull
     * @rdbSize 2
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double BACDSU;

    /**
     * Office Mgr Employee Nbr.
     * @rdbPhysicalName OMNRSU
     * @rdbNotNull
     * @rdbSize 7
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double OMNRSU;

    /**
     * Select for Invoicing
     * @rdbPhysicalName SLIVSU
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String SLIVSU;

    /**
     * Code Active Y/N
     * @rdbPhysicalName ACTVSU
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String ACTVSU;

    /**
     * Held for invoicing Y/N
     * @rdbPhysicalName HELDSU
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String HELDSU;

    /**
     * Held for payment ?
     * @rdbPhysicalName PPHLSU
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String PPHLSU;

    /**
     * Held for payroll ?
     * @rdbPhysicalName PYHLSU
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String PYHLSU;

    /**
     * Date Opened
     * @rdbPhysicalName DTOPSU
     * @rdbNotNull
     * @rdbSize 8
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double DTOPSU;

    /**
     * Date Closed
     * @rdbPhysicalName DTCLSU
     * @rdbNotNull
     * @rdbSize 8
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double DTCLSU;

    /**
     * DMFA0042-LocalUnitid
     * @rdbPhysicalName LUIDSU
     * @rdbNotNull
     * @rdbSize 10
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL 
     */
    private double LUIDSU;

    /**
     * AR collector
     * @rdbPhysicalName COLLECTRSU
     * @rdbNotNull
     * @rdbSize 8
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String COLLECTRSU;

    /**
     * Print Company
     * @rdbPhysicalName PRINT_CYSU
     * @rdbNotNull
     * @rdbSize 3
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL 
     */
    private double PRINT_CYSU;

    /**
     * Siècle de l'introduction
     * @rdbPhysicalName SINTSU
     * @rdbNotNull
     * @rdbSize 2
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double SINTSU;

    /**
     * Date de l'introduction
     * @rdbPhysicalName DINTSU
     * @rdbNotNull
     * @rdbSize 8
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double DINTSU;

    /**
     * Heure de l'introduction
     * @rdbPhysicalName CRTISU
     * @rdbNotNull
     * @rdbSize 6
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double CRTISU;

    /**
     * Identité de l'opératrice
     * @rdbPhysicalName IDENSU
     * @rdbNotNull
     * @rdbSize 10
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String IDENSU;

    /**
     * Date de la modification
     * @rdbPhysicalName DMODSU
     * @rdbNotNull
     * @rdbSize 8
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double DMODSU;

    /**
     * Heure de la modification
     * @rdbPhysicalName MDTISU
     * @rdbNotNull
     * @rdbSize 6
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double MDTISU;

    /**
     * Identité de l'opératrice
     * @rdbPhysicalName IMODSU
     * @rdbNotNull
     * @rdbSize 10
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String IMODSU;

    /**
     * Nombre de record
     * @rdbPhysicalName NBRLSU
     * @rdbNotNull
     * @rdbSize 7
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL 
     */
    private double NBRLSU;

    /**
     * Zone de controle
     * @rdbPhysicalName CH1LSU
     * @rdbNotNull
     * @rdbSize 15
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL 
     */
    private double CH1LSU;
	/**
	 * @return
	 */
	public String getACTVSU() {
		return ACTVSU;
	}

	/**
	 * @return
	 */
	public String getADRDSU() {
		return ADRDSU;
	}

	/**
	 * @return
	 */
	public double getBACDSU() {
		return BACDSU;
	}

	/**
	 * @return
	 */
	public double getBCCDSU() {
		return BCCDSU;
	}

	/**
	 * @return
	 */
	public double getCH1LSU() {
		return CH1LSU;
	}

	/**
	 * @return
	 */
	public String getCLANSU() {
		return CLANSU;
	}

	/**
	 * @return
	 */
	public String getCOLLECTRSU() {
		return COLLECTRSU;
	}

	/**
	 * @return
	 */
	public String getCPADSU() {
		return CPADSU;
	}

	/**
	 * @return
	 */
	public double getCRTISU() {
		return CRTISU;
	}

	/**
	 * @return
	 */
	public String getDICDSU() {
		return DICDSU;
	}

	/**
	 * @return
	 */
	public double getDINTSU() {
		return DINTSU;
	}

	/**
	 * @return
	 */
	public double getDMODSU() {
		return DMODSU;
	}

	/**
	 * @return
	 */
	public double getDNOCSU() {
		return DNOCSU;
	}

	/**
	 * @return
	 */
	public double getDTCLSU() {
		return DTCLSU;
	}

	/**
	 * @return
	 */
	public double getDTOPSU() {
		return DTOPSU;
	}

	/**
	 * @return
	 */
	public double getFXNRSU() {
		return FXNRSU;
	}

	/**
	 * @return
	 */
	public String getHELDSU() {
		return HELDSU;
	}

	/**
	 * @return
	 */
	public String getIDENSU() {
		return IDENSU;
	}

	/**
	 * @return
	 */
	public String getIMODSU() {
		return IMODSU;
	}

	/**
	 * @return
	 */
	public String getLISUSU() {
		return LISUSU;
	}

	/**
	 * @return
	 */
	public String getLOCDSU() {
		return LOCDSU;
	}

	/**
	 * @return
	 */
	public String getLONGNAMESU() {
		return LONGNAMESU;
	}

	/**
	 * @return
	 */
	public double getLUIDSU() {
		return LUIDSU;
	}

	/**
	 * @return
	 */
	public double getMDTISU() {
		return MDTISU;
	}

	/**
	 * @return
	 */
	public String getNBODSU() {
		return NBODSU;
	}

	/**
	 * @return
	 */
	public double getNBRLSU() {
		return NBRLSU;
	}

	/**
	 * @return
	 */
	public String getNOMCSU() {
		return NOMCSU;
	}

	/**
	 * @return
	 */
	public String getNOMPSU() {
		return NOMPSU;
	}

	/**
	 * @return
	 */
	public String getNOMRSU() {
		return NOMRSU;
	}

	/**
	 * @return
	 */
	public String getNPODSU() {
		return NPODSU;
	}

	/**
	 * @return
	 */
	public double getNREGSU() {
		return NREGSU;
	}

	/**
	 * @return
	 */
	public double getNSOCSU() {
		return NSOCSU;
	}

	/**
	 * @return
	 */
	public String getOMCDSU() {
		return OMCDSU;
	}

	/**
	 * @return
	 */
	public double getOMNRSU() {
		return OMNRSU;
	}

	/**
	 * @return
	 */
	public String getPHNRSU() {
		return PHNRSU;
	}

	/**
	 * @return
	 */
	public String getPPHLSU() {
		return PPHLSU;
	}

	/**
	 * @return
	 */
	public double getPRINT_CYSU() {
		return PRINT_CYSU;
	}

	/**
	 * @return
	 */
	public String getPYHLSU() {
		return PYHLSU;
	}

	/**
	 * @return
	 */
	public double getSINTSU() {
		return SINTSU;
	}

	/**
	 * @return
	 */
	public String getSLANSU() {
		return SLANSU;
	}

	/**
	 * @return
	 */
	public String getSLIVSU() {
		return SLIVSU;
	}

	/**
	 * @return
	 */
	public double getSOCCSU() {
		return SOCCSU;
	}

	/**
	 * @return
	 */
	public double getSUCCSU() {
		return SUCCSU;
	}

	/**
	 * @return
	 */
	public double getSUCGSU() {
		return SUCGSU;
	}

	/**
	 * @param string
	 */
	public void setACTVSU(String string) {
		ACTVSU = string;
	}

	/**
	 * @param string
	 */
	public void setADRDSU(String string) {
		ADRDSU = string;
	}

	/**
	 * @param d
	 */
	public void setBACDSU(double d) {
		BACDSU = d;
	}

	/**
	 * @param d
	 */
	public void setBCCDSU(double d) {
		BCCDSU = d;
	}

	/**
	 * @param d
	 */
	public void setCH1LSU(double d) {
		CH1LSU = d;
	}

	/**
	 * @param string
	 */
	public void setCLANSU(String string) {
		CLANSU = string;
	}

	/**
	 * @param string
	 */
	public void setCOLLECTRSU(String string) {
		COLLECTRSU = string;
	}

	/**
	 * @param string
	 */
	public void setCPADSU(String string) {
		CPADSU = string;
	}

	/**
	 * @param d
	 */
	public void setCRTISU(double d) {
		CRTISU = d;
	}

	/**
	 * @param string
	 */
	public void setDICDSU(String string) {
		DICDSU = string;
	}

	/**
	 * @param d
	 */
	public void setDINTSU(double d) {
		DINTSU = d;
	}

	/**
	 * @param d
	 */
	public void setDMODSU(double d) {
		DMODSU = d;
	}

	/**
	 * @param d
	 */
	public void setDNOCSU(double d) {
		DNOCSU = d;
	}

	/**
	 * @param d
	 */
	public void setDTCLSU(double d) {
		DTCLSU = d;
	}

	/**
	 * @param d
	 */
	public void setDTOPSU(double d) {
		DTOPSU = d;
	}

	/**
	 * @param d
	 */
	public void setFXNRSU(double d) {
		FXNRSU = d;
	}

	/**
	 * @param string
	 */
	public void setHELDSU(String string) {
		HELDSU = string;
	}

	/**
	 * @param string
	 */
	public void setIDENSU(String string) {
		IDENSU = string;
	}

	/**
	 * @param string
	 */
	public void setIMODSU(String string) {
		IMODSU = string;
	}

	/**
	 * @param string
	 */
	public void setLISUSU(String string) {
		LISUSU = string;
	}

	/**
	 * @param string
	 */
	public void setLOCDSU(String string) {
		LOCDSU = string;
	}

	/**
	 * @param string
	 */
	public void setLONGNAMESU(String string) {
		LONGNAMESU = string;
	}

	/**
	 * @param d
	 */
	public void setLUIDSU(double d) {
		LUIDSU = d;
	}

	/**
	 * @param d
	 */
	public void setMDTISU(double d) {
		MDTISU = d;
	}

	/**
	 * @param string
	 */
	public void setNBODSU(String string) {
		NBODSU = string;
	}

	/**
	 * @param d
	 */
	public void setNBRLSU(double d) {
		NBRLSU = d;
	}

	/**
	 * @param string
	 */
	public void setNOMCSU(String string) {
		NOMCSU = string;
	}

	/**
	 * @param string
	 */
	public void setNOMPSU(String string) {
		NOMPSU = string;
	}

	/**
	 * @param string
	 */
	public void setNOMRSU(String string) {
		NOMRSU = string;
	}

	/**
	 * @param string
	 */
	public void setNPODSU(String string) {
		NPODSU = string;
	}

	/**
	 * @param d
	 */
	public void setNREGSU(double d) {
		NREGSU = d;
	}

	/**
	 * @param d
	 */
	public void setNSOCSU(double d) {
		NSOCSU = d;
	}

	/**
	 * @param string
	 */
	public void setOMCDSU(String string) {
		OMCDSU = string;
	}

	/**
	 * @param d
	 */
	public void setOMNRSU(double d) {
		OMNRSU = d;
	}

	/**
	 * @param string
	 */
	public void setPHNRSU(String string) {
		PHNRSU = string;
	}

	/**
	 * @param string
	 */
	public void setPPHLSU(String string) {
		PPHLSU = string;
	}

	/**
	 * @param d
	 */
	public void setPRINT_CYSU(double d) {
		PRINT_CYSU = d;
	}

	/**
	 * @param string
	 */
	public void setPYHLSU(String string) {
		PYHLSU = string;
	}

	/**
	 * @param d
	 */
	public void setSINTSU(double d) {
		SINTSU = d;
	}

	/**
	 * @param string
	 */
	public void setSLANSU(String string) {
		SLANSU = string;
	}

	/**
	 * @param string
	 */
	public void setSLIVSU(String string) {
		SLIVSU = string;
	}

	/**
	 * @param d
	 */
	public void setSOCCSU(double d) {
		SOCCSU = d;
	}

	/**
	 * @param d
	 */
	public void setSUCCSU(double d) {
		SUCCSU = d;
	}

	/**
	 * @param d
	 */
	public void setSUCGSU(double d) {
		SUCGSU = d;
	}

}
