/* Generated by Together */

package database.datastore;

/**
 * @persistent
 * @rdbPhysicalName WHTEMPP 
 */
public class WHTEMPP {
    public WHTEMPP() {
    }

    /**
     * Adecco Company Code
     * @rdbPhysicalName ADCYW4
     * @rdbNotNull
     * @rdbSize 3
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double ADCYW4;

    /**
     * Temp Number
     * @rdbPhysicalName TEMPW4
     * @rdbNotNull
     * @rdbSize 7
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double TEMPW4;

    /**
     * Family Name
     * @rdbPhysicalName FANAW4
     * @rdbNotNull
     * @rdbSize 30
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String FANAW4;

    /**
     * First Name
     * @rdbPhysicalName FINAW4
     * @rdbNotNull
     * @rdbSize 30
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String FINAW4;

    /**
     * Street
     * @rdbPhysicalName STRTW4
     * @rdbNotNull
     * @rdbSize 30
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String STRTW4;

    /**
     * House Number
     * @rdbPhysicalName HSNRW4
     * @rdbNotNull
     * @rdbSize 5
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String HSNRW4;

    /**
     * Mail box
     * @rdbPhysicalName MBOXW4
     * @rdbNotNull
     * @rdbSize 6
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String MBOXW4;

    /**
     * Country Code
     * @rdbPhysicalName CTYCW4
     * @rdbNotNull
     * @rdbSize 3
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CTYCW4;

    /**
     * Code Zip
     * @rdbPhysicalName CZIPW4
     * @rdbNotNull
     * @rdbSize 10
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CZIPW4;

    /**
     * City
     * @rdbPhysicalName CITYW4
     * @rdbNotNull
     * @rdbSize 30
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CITYW4;

    /**
     * Phone number
     * @rdbPhysicalName PHONW4
     * @rdbNotNull
     * @rdbSize 15
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String PHONW4;

    /**
     * Language Code
     * @rdbPhysicalName LGCDW4
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String LGCDW4;

    /**
     * National Registration Number
     * @rdbPhysicalName NNUMW4
     * @rdbNotNull
     * @rdbSize 11
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double NNUMW4;

    /**
     * SIS Number
     * @rdbPhysicalName SSNRW4
     * @rdbNotNull
     * @rdbSize 10
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double SSNRW4;

    /**
     * Birth date
     * @rdbPhysicalName DTBIW4
     * @rdbNotNull
     * @rdbSize 8
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double DTBIW4;

    /**
     * Male or Female
     * @rdbPhysicalName SEXXW4
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String SEXXW4;

    /**
     * Creation User for Record
     * @rdbPhysicalName CRUSW4
     * @rdbNotNull
     * @rdbSize 10
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CRUSW4;

    /**
     * Creation Date for Record
     * @rdbPhysicalName CRDTW4
     * @rdbNotNull
     * @rdbSize 8
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double CRDTW4;

    /**
     * Creation Time for Record
     * @rdbPhysicalName CRTIW4
     * @rdbNotNull
     * @rdbSize 6
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double CRTIW4;

    /**
     * Last Change User for Record
     * @rdbPhysicalName CHUSW4
     * @rdbNotNull
     * @rdbSize 10
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String CHUSW4;

    /**
     * Last Change Date for Record
     * @rdbPhysicalName CHDTW4
     * @rdbNotNull
     * @rdbSize 8
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double CHDTW4;

    /**
     * Last Change Time for Record
     * @rdbPhysicalName CHTIW4
     * @rdbNotNull
     * @rdbSize 6
     * @rdbDigits 0
     * @rdbLogicalType NUMERIC 
     */
    private double CHTIW4;
	/**
	 * @return
	 */
	public double getADCYW4() {
		return ADCYW4;
	}

	/**
	 * @return
	 */
	public double getCHDTW4() {
		return CHDTW4;
	}

	/**
	 * @return
	 */
	public double getCHTIW4() {
		return CHTIW4;
	}

	/**
	 * @return
	 */
	public String getCHUSW4() {
		return CHUSW4;
	}

	/**
	 * @return
	 */
	public String getCITYW4() {
		return CITYW4;
	}

	/**
	 * @return
	 */
	public double getCRDTW4() {
		return CRDTW4;
	}

	/**
	 * @return
	 */
	public double getCRTIW4() {
		return CRTIW4;
	}

	/**
	 * @return
	 */
	public String getCRUSW4() {
		return CRUSW4;
	}

	/**
	 * @return
	 */
	public String getCTYCW4() {
		return CTYCW4;
	}

	/**
	 * @return
	 */
	public String getCZIPW4() {
		return CZIPW4;
	}

	/**
	 * @return
	 */
	public double getDTBIW4() {
		return DTBIW4;
	}

	/**
	 * @return
	 */
	public String getFANAW4() {
		return FANAW4;
	}

	/**
	 * @return
	 */
	public String getFINAW4() {
		return FINAW4;
	}

	/**
	 * @return
	 */
	public String getHSNRW4() {
		return HSNRW4;
	}

	/**
	 * @return
	 */
	public String getLGCDW4() {
		return LGCDW4;
	}

	/**
	 * @return
	 */
	public String getMBOXW4() {
		return MBOXW4;
	}

	/**
	 * @return
	 */
	public double getNNUMW4() {
		return NNUMW4;
	}

	/**
	 * @return
	 */
	public String getPHONW4() {
		return PHONW4;
	}

	/**
	 * @return
	 */
	public String getSEXXW4() {
		return SEXXW4;
	}

	/**
	 * @return
	 */
	public double getSSNRW4() {
		return SSNRW4;
	}

	/**
	 * @return
	 */
	public String getSTRTW4() {
		return STRTW4;
	}

	/**
	 * @return
	 */
	public double getTEMPW4() {
		return TEMPW4;
	}

	/**
	 * @param d
	 */
	public void setADCYW4(double d) {
		ADCYW4 = d;
	}

	/**
	 * @param d
	 */
	public void setCHDTW4(double d) {
		CHDTW4 = d;
	}

	/**
	 * @param d
	 */
	public void setCHTIW4(double d) {
		CHTIW4 = d;
	}

	/**
	 * @param string
	 */
	public void setCHUSW4(String string) {
		CHUSW4 = string;
	}

	/**
	 * @param string
	 */
	public void setCITYW4(String string) {
		CITYW4 = string;
	}

	/**
	 * @param d
	 */
	public void setCRDTW4(double d) {
		CRDTW4 = d;
	}

	/**
	 * @param d
	 */
	public void setCRTIW4(double d) {
		CRTIW4 = d;
	}

	/**
	 * @param string
	 */
	public void setCRUSW4(String string) {
		CRUSW4 = string;
	}

	/**
	 * @param string
	 */
	public void setCTYCW4(String string) {
		CTYCW4 = string;
	}

	/**
	 * @param string
	 */
	public void setCZIPW4(String string) {
		CZIPW4 = string;
	}

	/**
	 * @param d
	 */
	public void setDTBIW4(double d) {
		DTBIW4 = d;
	}

	/**
	 * @param string
	 */
	public void setFANAW4(String string) {
		FANAW4 = string;
	}

	/**
	 * @param string
	 */
	public void setFINAW4(String string) {
		FINAW4 = string;
	}

	/**
	 * @param string
	 */
	public void setHSNRW4(String string) {
		HSNRW4 = string;
	}

	/**
	 * @param string
	 */
	public void setLGCDW4(String string) {
		LGCDW4 = string;
	}

	/**
	 * @param string
	 */
	public void setMBOXW4(String string) {
		MBOXW4 = string;
	}

	/**
	 * @param d
	 */
	public void setNNUMW4(double d) {
		NNUMW4 = d;
	}

	/**
	 * @param string
	 */
	public void setPHONW4(String string) {
		PHONW4 = string;
	}

	/**
	 * @param string
	 */
	public void setSEXXW4(String string) {
		SEXXW4 = string;
	}

	/**
	 * @param d
	 */
	public void setSSNRW4(double d) {
		SSNRW4 = d;
	}

	/**
	 * @param string
	 */
	public void setSTRTW4(String string) {
		STRTW4 = string;
	}

	/**
	 * @param d
	 */
	public void setTEMPW4(double d) {
		TEMPW4 = d;
	}

}
