/* Generated by Together */
package ch4;
public class AnimalGame {
    public static void main(String[] argv) {
        Animals animals = new Animals();
        int nbrLegs = 0;
        while (nbrLegs != -9999) {
            System.out.println("How many legs do you have?");
            nbrLegs = ReadIntegers.readNextInteger();
            switch (nbrLegs) {
                case 1:
                    System.out.println("\tyou are a " + animals.getRandomOneLegAnimal());break;
                case 2:
                    System.out.println("\tyou are a " + animals.getRandomTwoLegAnimal());break;
                case 4:
                    System.out.println("\tyou are a " + animals.getRandomFourLegAnimal());break;
                case -9999:
                    System.out.println("\tBye you animal");break;
                default:System.out.println("\tWhat kind of animal are you anyway?");
            }
			System.out.println();
        }
    }
}
