/* Generated by Together */
package ch9;

import ch9.dates.DatFmt;
import ch9.dates.DateDelta;

import java.util.GregorianCalendar;
 
public class Car {
    public Car(int carPlate) {
        this.carPlate = carPlate;
        carStatus = STATUS_NOTRENTED;
        carRentalStart = null;
        carRentalEnd = null;
    }

    public void rent() {
        carStatus = STATUS_RENTED;
        carRentalStart = new GregorianCalendar();
    }

    public DateDelta returnIt() {
        carStatus = STATUS_NOTRENTED;
        carRentalEnd = new GregorianCalendar();
        return new DateDelta(carRentalStart, carRentalEnd);
    }

    public void display() {
        DatFmt fmt = new DatFmt();
        System.out.println("Plate: " + carPlate);
        if (carStatus == STATUS_RENTED)
            System.out.println("\tRented on: " + fmt.format(carRentalStart.getTime()));
    }
    
    public String toString(){
    	return "Car "+getPlate()+" is rented on "+ getCarRentalStart().getTime();
    }

    public int getPlate() { return carPlate; }

    public char getStatus() { return carStatus; }

    public boolean isRented() {
        return carStatus == STATUS_RENTED;
    }

    private int carPlate;
    private char carStatus;
    private GregorianCalendar carRentalStart, carRentalEnd;
    public static final char STATUS_RENTED = 'R';
    public static final char STATUS_NOTRENTED = 'A';
	/**
	 * @return
	 */
	public GregorianCalendar getCarRentalEnd() {
		return carRentalEnd;
	}

	/**
	 * @return
	 */
	public GregorianCalendar getCarRentalStart() {
		return carRentalStart;
	}

}
