/* Generated by Together */
package ch8;

import java.text.SimpleDateFormat;
import java.util.Date;

public class TimFmt {
    public TimFmt(int format){
        this();
        this.format = format;
    }

    public TimFmt() {
    }

    public TimFmt(int format, char separator) {
        this(format);
        this.separator = separator;
    }
    public int getFormat(){
            return format;
        }

    public void setFormat(int format){
            this.format = format;
        }

    public char getSeparator(){
            return separator;
        }

    public void setSeparator(char separator){
        	if (separator == -1)
                separator = separator;
            this.separator = separator;
        }

    public String format(Date time) {
		SimpleDateFormat simpel = new SimpleDateFormat(formats[format]);
        String timeString = simpel.format(time);
        timeString = timeString.replace('/',defaultSeparators[format]);
        return timeString;
    }

    public static void main(String[] argv) {
        TimFmt me = new TimFmt();
        Date time= new Date();
        System.out.println(me.format(time));
	    System.out.println("Default separator\n");
        for(int i = TimFmt_HMS; i<=TimFmt_JIS; i++){
            me.setFormat(i);
	        System.out.println(me.format(time));
        }

	    System.out.println("Forced separator\n");
        for(int i = TimFmt_HMS; i<=TimFmt_JIS; i++){
            me.setFormat(i);
            me.setSeparator('.');
	        System.out.println(me.format(time));
        }
    }

    public final static int TimFmt_HMS = 0;
    public final static int TimFmt_USA = 1;
    public final static int TimFmt_EUR = 2;
    public final static int TimFmt_ISO = 3;
    public final static int TimFmt_JIS = 4;

    private int format = TimFmt_ISO;
    private char separator = (char)-1;

    private String [] formats = {"hh:mm:ss", "hh:mm a", "hh.mm.ss", "hh.mm.ss", "hh:mm:ss"};
	private char [] defaultSeparators = {':',':','.','.',':'};

}
