/* Generated by Together */
package ch12;

import javax.swing.*;
import java.awt.*;
import java.util.Enumeration;

public class DisplayWindow extends JDialog implements CommonButtonInterface, Runnable {
    public DisplayWindow(JFrame parent) {
        super(parent, "Display Rented Cars", true);
        mainWindow = (RentalGUI)parent;
        rental = mainWindow.getRentalObject();
        getContentPane().setLayout(new BorderLayout());
        buttons = new CommonButtons(this);
        buttons.setOKButtonText("Ok");
		defMod = new DefaultListModel();
        list = new JList(defMod);
        list.setVisibleRowCount(10);
        closer = new FrameListener(this, false);
        JScrollPane scrlPane = new JScrollPane(list);
        getContentPane().add(scrlPane, BorderLayout.CENTER);
        getContentPane().add(buttons, BorderLayout.SOUTH);
        addWindowListener(closer);
        setLocation(300, 200);
        pack();
        Thread thread = new Thread(this);
        thread.start();
    }

    public void cancelPressed() {
        closer.closeWindow();
        rental.stopThread();
    }

    public void okPressed() {
        closer.closeWindow();
    }

    public void run() {
        Enumeration en = rental.getRentedEnumeration();
        while (en.hasMoreElements()) {
            defMod.addElement(en.nextElement());
        }
    }

    private FrameListener closer;
    private CommonButtons buttons;
    private JList list;
    private RentalMethods rental;
    private RentalGUI mainWindow;
    private DefaultListModel defMod;
}
