/* Generated by Together */
package ch12;

import javax.swing.*;

public class PlateEntry extends JTextField {
    public PlateEntry() {
        super(PlateEntryModel.MAXLENGTH);
        super.setDocument(model);
    }

    public boolean isValid() {
        return (getText().length() == PlateEntryModel.MAXLENGTH);
    }

    protected PlateEntryModel model = new PlateEntryModel();
}
