/* Generated by Together */
package ch12;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class RentalGUI extends JFrame implements ActionListener {
    public RentalGUI() {
        super("Rental Program");
        buttons = new JPanel();
        buttons.setLayout(new GridLayout(4, 1));
        rentButton = new BigButton("Rent...");
        rentButton.addActionListener(this);
        returnButton = new BigButton("Return...");
        returnButton.addActionListener(this);
        displayButton = new BigButton("Display...");
        displayButton.addActionListener(this);
        closeButton = new BigButton("Close...");
        closeButton.addActionListener(this);
        buttons.add(rentButton);
        buttons.add(returnButton);
        buttons.add(displayButton);
        buttons.add(closeButton);
        infoArea = new InfoArea();
        getContentPane().add(buttons, BorderLayout.CENTER);
        getContentPane().add(infoArea, BorderLayout.SOUTH);
        setSize(175, 300);
        setLocation(200, 300);
        closer = new FrameListener(this, true);
        addWindowListener(closer);
        rental = new RentalMethods();
        rental.populateLot();
        setVisible(true);
    }

    public RentalMethods getRentalObject() {
        return rental;
    }

    public InfoArea getInfoArea() {
        return infoArea;
    }

    public void actionPerformed(ActionEvent evt) {
        Object srcObj = evt.getSource();
        if (srcObj.equals(rentButton)) {
            RentWindow rentWindow = new RentWindow(this);
            rentWindow.setVisible(true);
        }
        else if (srcObj.equals(returnButton)) {
            ReturnWindow returnWindow = new ReturnWindow(this);
            returnWindow.setVisible(true);
        }
        else if (srcObj.equals(displayButton)) {
            DisplayWindowInTable displayWindow = new DisplayWindowInTable(this);
            displayWindow.setVisible(true);
        }
        else if (srcObj.equals(closeButton)) { closer.closeWindow(); }
    }

    public static void main(String args[]) {
        RentalGUI app = new RentalGUI();
    }

    private BigButton rentButton, returnButton, displayButton, closeButton;
    private InfoArea infoArea;
    private FrameListener closer;
    private JPanel buttons;
    private RentalMethods rental;
}
