/* Generated by Together */
package ch12;
import javax.swing.*;
import java.awt.*;

public class BigButton extends JButton {
    public BigButton(String text) {
        super(text);
        Font f = new Font("SansSerif", Font.BOLD, 18);
        setFont(f);
        setBorder(BorderFactory.createRaisedBevelBorder());
    }
}
