/* Generated by Together */
package ch12;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class CommonButtons extends JPanel implements ActionListener {
    public CommonButtons(CommonButtonInterface caller) {
        super();
        this.caller = caller;
        okButton = new JButton("OK");
        okButton.setBorder(BorderFactory.createRaisedBevelBorder());
        cancelButton = new JButton("Cancel");
        cancelButton.setBorder(BorderFactory.createRaisedBevelBorder());
        setLayout(new GridLayout(1, 2));
        add(okButton);
        add(cancelButton);
        okButton.addActionListener(this);
        cancelButton.addActionListener(this);
    }

    public void actionPerformed(ActionEvent evt) {
        Object srcObj = evt.getSource();
        if (srcObj.equals(okButton)) { caller.okPressed(); }
        else if (srcObj.equals(cancelButton)) { caller.cancelPressed(); }
    }

    public void setOKButtonText(String text) {
        okButton.setLabel(text);
    }

    private JButton okButton;
    private JButton cancelButton;
    private CommonButtonInterface caller;
}
