/* Generated by Together */
package ch12;
import javax.swing.*;
import java.awt.*;

public class InfoArea extends JTextField {
    public InfoArea() {
        setBackground(Color.cyan);
        setEditable(false);
        setBorder(BorderFactory.createLoweredBevelBorder());
    }
}
