/* Generated by Together */
package ch12;

import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;
import java.awt.*;

public class PlateEntryModel extends PlainDocument {
    public final static int MAXLENGTH = 6;

    public void insertString(int offset, String string, AttributeSet attrs) throws BadLocationException {
        boolean error = false;
        if (string == null)
            super.insertString(offset, string, attrs);
        else if (string.length() > MAXLENGTH)
            error = true;
        else {
            int i = 0;
            while (i < string.length() && !error) {
                if (string.charAt(i) < '0' || string.charAt(i) > '9')
                    error = true;
                i++;
            }
        }
        if (error)
            Toolkit.getDefaultToolkit().beep();
        else
            super.insertString(offset, string, attrs);
    }
}
