/* Generated by Together */
package ch12;

import ch12.dates.DateDelta;

import javax.swing.*;
import java.awt.*;

public class ReturnWindow extends JDialog implements CommonButtonInterface {
    public ReturnWindow(JFrame parent) {
        super(parent, "Return A Car", true);
        mainWindow = (RentalGUI)parent;
        rental = mainWindow.getRentalObject();
        getContentPane().setLayout(new BorderLayout());
        plateLabel = new JLabel("Plate number");
        plateEntry = new PlateEntry();
        labeledPlateEntry = new LabeledComponent(plateLabel, plateEntry);
        buttons = new CommonButtons(this);
        buttons.setOKButtonText("Return");
        getContentPane().add(labeledPlateEntry, BorderLayout.CENTER);
        JPanel bottomPanel = new JPanel();
        bottomPanel.setLayout(new GridLayout(2, 1));
        infoArea = new InfoArea();
        bottomPanel.add(buttons);
        bottomPanel.add(infoArea);
        getContentPane().add(bottomPanel, BorderLayout.SOUTH);
        closer = new FrameListener(this, false);
        addWindowListener(closer);
        setLocation(300, 200);
        pack();
    }

    public void cancelPressed() { closer.closeWindow(); }

    public void okPressed() {
        DateDelta delta = rental.returnCar(plateEntry.getText().trim());
        if (delta != null) {
            mainWindow.getInfoArea().setText("Car returned. Rented for " + delta);
            closer.closeWindow();
        }
        else {
            infoArea.setText("Car not found or not rented");
            plateEntry.requestFocus();
            Toolkit.getDefaultToolkit().beep();
        }
    }

    private FrameListener closer;
    private CommonButtons buttons;
    private JLabel plateLabel;
    private PlateEntry plateEntry;
    private LabeledComponent labeledPlateEntry;
    private InfoArea infoArea;
    private RentalGUI mainWindow;
    private RentalMethods rental;
}
