/* Generated by Together */
package ch5;
public class UseDataTypes {
    public static void main(String[] argv) {
        DataTypes dt = new DataTypes();
        dt.shortVar = 200;
        dt.displayVars();
    }
}
